// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/GameStateTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UGameStateTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FGameStateType>>();

    TSharedPtr<FTableCache<FGameStateType>> GameStateTable = Data->GetOrAdd(TableName);
    GameStateTable->AddUniqueConstraint<uint32>("id", [](const FGameStateType& Row) -> const uint32& {
        return Row.Id; });

    Id = NewObject<UGameStateIdUniqueIndex>(this);
    Id->SetCache(GameStateTable);

    /***/
}

FTableAppliedDiff<FGameStateType> UGameStateTable::Update(TArray<FWithBsatn<FGameStateType>> InsertsRef, TArray<FWithBsatn<FGameStateType>> DeletesRef)
{
    FTableAppliedDiff<FGameStateType> Diff = BaseUpdate<FGameStateType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint32>(
        [](const FGameStateType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UGameStateTable::Count() const
{
    return GetRowCountFromTable<FGameStateType>(Data, TableName);
}

TArray<FGameStateType> UGameStateTable::Iter() const
{
    return GetAllRowsFromTable<FGameStateType>(Data, TableName);
}
