// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/GuessResultTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UGuessResultTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FGuessResultType>>();

    TSharedPtr<FTableCache<FGuessResultType>> GuessResultTable = Data->GetOrAdd(TableName);
    GuessResultTable->AddUniqueConstraint<uint64>("id", [](const FGuessResultType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UGuessResultIdUniqueIndex>(this);
    Id->SetCache(GuessResultTable);

    // Register a new multi-key B-Tree index named "round" on the GuessResultTable.
    GuessResultTable->AddMultiKeyBTreeIndex<TTuple<uint32>>(
        TEXT("round"),
        [](const FGuessResultType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.Round);
        }
    );

    Round = NewObject<UGuessResultRoundIndex>(this);
    Round->SetCache(GuessResultTable);

    /***/
}

FTableAppliedDiff<FGuessResultType> UGuessResultTable::Update(TArray<FWithBsatn<FGuessResultType>> InsertsRef, TArray<FWithBsatn<FGuessResultType>> DeletesRef)
{
    FTableAppliedDiff<FGuessResultType> Diff = BaseUpdate<FGuessResultType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FGuessResultType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UGuessResultTable::Count() const
{
    return GetRowCountFromTable<FGuessResultType>(Data, TableName);
}

TArray<FGuessResultType> UGuessResultTable::Iter() const
{
    return GetAllRowsFromTable<FGuessResultType>(Data, TableName);
}
