// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/UnrealPlayerStatsTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UUnrealPlayerStatsTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FUnrealPlayerStatsType>>();

    TSharedPtr<FTableCache<FUnrealPlayerStatsType>> UnrealPlayerStatsTable = Data->GetOrAdd(TableName);
    UnrealPlayerStatsTable->AddUniqueConstraint<uint32>("player_number", [](const FUnrealPlayerStatsType& Row) -> const uint32& {
        return Row.PlayerNumber; });

    PlayerNumber = NewObject<UUnrealPlayerStatsPlayerNumberUniqueIndex>(this);
    PlayerNumber->SetCache(UnrealPlayerStatsTable);

    /***/
}

FTableAppliedDiff<FUnrealPlayerStatsType> UUnrealPlayerStatsTable::Update(TArray<FWithBsatn<FUnrealPlayerStatsType>> InsertsRef, TArray<FWithBsatn<FUnrealPlayerStatsType>> DeletesRef)
{
    FTableAppliedDiff<FUnrealPlayerStatsType> Diff = BaseUpdate<FUnrealPlayerStatsType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint32>(
        [](const FUnrealPlayerStatsType& Row) 
        {
            return Row.PlayerNumber; 
        }
    );

    return Diff;
}

int32 UUnrealPlayerStatsTable::Count() const
{
    return GetRowCountFromTable<FUnrealPlayerStatsType>(Data, TableName);
}

TArray<FUnrealPlayerStatsType> UUnrealPlayerStatsTable::Iter() const
{
    return GetAllRowsFromTable<FUnrealPlayerStatsType>(Data, TableName);
}
