// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/UnrealRoundResultTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UUnrealRoundResultTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FUnrealRoundResultType>>();

    TSharedPtr<FTableCache<FUnrealRoundResultType>> UnrealRoundResultTable = Data->GetOrAdd(TableName);
    UnrealRoundResultTable->AddUniqueConstraint<uint64>("id", [](const FUnrealRoundResultType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UUnrealRoundResultIdUniqueIndex>(this);
    Id->SetCache(UnrealRoundResultTable);

    // Register a new multi-key B-Tree index named "round" on the UnrealRoundResultTable.
    UnrealRoundResultTable->AddMultiKeyBTreeIndex<TTuple<uint32>>(
        TEXT("round"),
        [](const FUnrealRoundResultType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.Round);
        }
    );

    Round = NewObject<UUnrealRoundResultRoundIndex>(this);
    Round->SetCache(UnrealRoundResultTable);

    // Register a new multi-key B-Tree index named "session_id" on the UnrealRoundResultTable.
    UnrealRoundResultTable->AddMultiKeyBTreeIndex<TTuple<FString>>(
        TEXT("session_id"),
        [](const FUnrealRoundResultType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.SessionId);
        }
    );

    SessionId = NewObject<UUnrealRoundResultSessionIdIndex>(this);
    SessionId->SetCache(UnrealRoundResultTable);

    /***/
}

FTableAppliedDiff<FUnrealRoundResultType> UUnrealRoundResultTable::Update(TArray<FWithBsatn<FUnrealRoundResultType>> InsertsRef, TArray<FWithBsatn<FUnrealRoundResultType>> DeletesRef)
{
    FTableAppliedDiff<FUnrealRoundResultType> Diff = BaseUpdate<FUnrealRoundResultType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FUnrealRoundResultType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UUnrealRoundResultTable::Count() const
{
    return GetRowCountFromTable<FUnrealRoundResultType>(Data, TableName);
}

TArray<FUnrealRoundResultType> UUnrealRoundResultTable::Iter() const
{
    return GetAllRowsFromTable<FUnrealRoundResultType>(Data, TableName);
}
