// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/UnrealGuessLogTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UUnrealGuessLogTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FUnrealGuessLogType>>();

    TSharedPtr<FTableCache<FUnrealGuessLogType>> UnrealGuessLogTable = Data->GetOrAdd(TableName);
    UnrealGuessLogTable->AddUniqueConstraint<uint64>("id", [](const FUnrealGuessLogType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UUnrealGuessLogIdUniqueIndex>(this);
    Id->SetCache(UnrealGuessLogTable);

    // Register a new multi-key B-Tree index named "player_number" on the UnrealGuessLogTable.
    UnrealGuessLogTable->AddMultiKeyBTreeIndex<TTuple<uint32>>(
        TEXT("player_number"),
        [](const FUnrealGuessLogType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.PlayerNumber);
        }
    );

    PlayerNumber = NewObject<UUnrealGuessLogPlayerNumberIndex>(this);
    PlayerNumber->SetCache(UnrealGuessLogTable);

    // Register a new multi-key B-Tree index named "round" on the UnrealGuessLogTable.
    UnrealGuessLogTable->AddMultiKeyBTreeIndex<TTuple<uint32>>(
        TEXT("round"),
        [](const FUnrealGuessLogType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.Round);
        }
    );

    Round = NewObject<UUnrealGuessLogRoundIndex>(this);
    Round->SetCache(UnrealGuessLogTable);

    // Register a new multi-key B-Tree index named "session_id" on the UnrealGuessLogTable.
    UnrealGuessLogTable->AddMultiKeyBTreeIndex<TTuple<FString>>(
        TEXT("session_id"),
        [](const FUnrealGuessLogType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.SessionId);
        }
    );

    SessionId = NewObject<UUnrealGuessLogSessionIdIndex>(this);
    SessionId->SetCache(UnrealGuessLogTable);

    /***/
}

FTableAppliedDiff<FUnrealGuessLogType> UUnrealGuessLogTable::Update(TArray<FWithBsatn<FUnrealGuessLogType>> InsertsRef, TArray<FWithBsatn<FUnrealGuessLogType>> DeletesRef)
{
    FTableAppliedDiff<FUnrealGuessLogType> Diff = BaseUpdate<FUnrealGuessLogType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FUnrealGuessLogType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UUnrealGuessLogTable::Count() const
{
    return GetRowCountFromTable<FUnrealGuessLogType>(Data, TableName);
}

TArray<FUnrealGuessLogType> UUnrealGuessLogTable::Iter() const
{
    return GetAllRowsFromTable<FUnrealGuessLogType>(Data, TableName);
}
