// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/GameStateType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "GameStateTable.g.generated.h"

UCLASS(Blueprintable)
class CH_4_API UGameStateIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FGameStateType, uint32, FTableCache<FGameStateType>> IdIndexHelper;

public:
    UGameStateIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a GameState by their unique id.
     * @param Key The id to search for.
     * @return The found FGameStateType, or a default-constructed FGameStateType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FGameStateType Find(uint32 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FGameStateType>> InGameStateCache)
    {
        IdIndexHelper.Cache = InGameStateCache;
    }
};
/***/

UCLASS(BlueprintType)
class CH_4_API UGameStateTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UGameStateIdUniqueIndex* Id;

    void PostInitialize();

    /** Update function for game_state table*/
    FTableAppliedDiff<FGameStateType> Update(TArray<FWithBsatn<FGameStateType>> InsertsRef, TArray<FWithBsatn<FGameStateType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FGameStateType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnGameStateInsert,
        const FEventContext&, Context,
        const FGameStateType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnGameStateUpdate,
        const FEventContext&, Context,
        const FGameStateType&, OldRow,
        const FGameStateType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnGameStateDelete,
        const FEventContext&, Context,
        const FGameStateType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnGameStateInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnGameStateUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnGameStateDelete OnDelete;

private:
    const FString TableName = TEXT("game_state");

    TSharedPtr<UClientCache<FGameStateType>> Data;
};
