// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/GuessResultType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "GuessResultTable.g.generated.h"

UCLASS(Blueprintable)
class CH_4_API UGuessResultIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FGuessResultType, uint64, FTableCache<FGuessResultType>> IdIndexHelper;

public:
    UGuessResultIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a GuessResult by their unique id.
     * @param Key The id to search for.
     * @return The found FGuessResultType, or a default-constructed FGuessResultType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FGuessResultType Find(uint64 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FGuessResultType>> InGuessResultCache)
    {
        IdIndexHelper.Cache = InGuessResultCache;
    }
};
/***/

UCLASS(Blueprintable)
class UGuessResultRoundIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FGuessResultType> Filter(const uint32& Round) const
    {
        TArray<FGuessResultType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<uint32>>(
            OutResults,
            TEXT("round"),
            MakeTuple(Round)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FGuessResultType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    // NOTE: Not exposed to Blueprint because some parameter types are not Blueprint-compatible
    void FilterRound(TArray<FGuessResultType>& OutResults, const uint32& Round)
    {
        OutResults = Filter(Round);
    }

    TSharedPtr<FTableCache<FGuessResultType>> LocalCache;
};

UCLASS(BlueprintType)
class CH_4_API UGuessResultTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UGuessResultIdUniqueIndex* Id;

    UPROPERTY(BlueprintReadOnly)
    UGuessResultRoundIndex* Round;

    void PostInitialize();

    /** Update function for guess_result table*/
    FTableAppliedDiff<FGuessResultType> Update(TArray<FWithBsatn<FGuessResultType>> InsertsRef, TArray<FWithBsatn<FGuessResultType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FGuessResultType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnGuessResultInsert,
        const FEventContext&, Context,
        const FGuessResultType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnGuessResultUpdate,
        const FEventContext&, Context,
        const FGuessResultType&, OldRow,
        const FGuessResultType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnGuessResultDelete,
        const FEventContext&, Context,
        const FGuessResultType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnGuessResultInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnGuessResultUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnGuessResultDelete OnDelete;

private:
    const FString TableName = TEXT("guess_result");

    TSharedPtr<UClientCache<FGuessResultType>> Data;
};
