// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/UnrealGuessLogType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "UnrealGuessLogTable.g.generated.h"

UCLASS(Blueprintable)
class CH_4_API UUnrealGuessLogIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FUnrealGuessLogType, uint64, FTableCache<FUnrealGuessLogType>> IdIndexHelper;

public:
    UUnrealGuessLogIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a UnrealGuessLog by their unique id.
     * @param Key The id to search for.
     * @return The found FUnrealGuessLogType, or a default-constructed FUnrealGuessLogType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FUnrealGuessLogType Find(uint64 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FUnrealGuessLogType>> InUnrealGuessLogCache)
    {
        IdIndexHelper.Cache = InUnrealGuessLogCache;
    }
};
/***/

UCLASS(Blueprintable)
class UUnrealGuessLogPlayerNumberIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FUnrealGuessLogType> Filter(const uint32& PlayerNumber) const
    {
        TArray<FUnrealGuessLogType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<uint32>>(
            OutResults,
            TEXT("player_number"),
            MakeTuple(PlayerNumber)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FUnrealGuessLogType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    // NOTE: Not exposed to Blueprint because some parameter types are not Blueprint-compatible
    void FilterPlayerNumber(TArray<FUnrealGuessLogType>& OutResults, const uint32& PlayerNumber)
    {
        OutResults = Filter(PlayerNumber);
    }

    TSharedPtr<FTableCache<FUnrealGuessLogType>> LocalCache;
};

UCLASS(Blueprintable)
class UUnrealGuessLogRoundIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FUnrealGuessLogType> Filter(const uint32& Round) const
    {
        TArray<FUnrealGuessLogType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<uint32>>(
            OutResults,
            TEXT("round"),
            MakeTuple(Round)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FUnrealGuessLogType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    // NOTE: Not exposed to Blueprint because some parameter types are not Blueprint-compatible
    void FilterRound(TArray<FUnrealGuessLogType>& OutResults, const uint32& Round)
    {
        OutResults = Filter(Round);
    }

    TSharedPtr<FTableCache<FUnrealGuessLogType>> LocalCache;
};

UCLASS(Blueprintable)
class UUnrealGuessLogSessionIdIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FUnrealGuessLogType> Filter(const FString& SessionId) const
    {
        TArray<FUnrealGuessLogType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<FString>>(
            OutResults,
            TEXT("session_id"),
            MakeTuple(SessionId)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FUnrealGuessLogType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    UFUNCTION(BlueprintCallable)
    void FilterSessionId(TArray<FUnrealGuessLogType>& OutResults, const FString& SessionId)
    {
        OutResults = Filter(SessionId);
    }

    TSharedPtr<FTableCache<FUnrealGuessLogType>> LocalCache;
};

UCLASS(BlueprintType)
class CH_4_API UUnrealGuessLogTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UUnrealGuessLogIdUniqueIndex* Id;

    UPROPERTY(BlueprintReadOnly)
    UUnrealGuessLogPlayerNumberIndex* PlayerNumber;

    UPROPERTY(BlueprintReadOnly)
    UUnrealGuessLogRoundIndex* Round;

    UPROPERTY(BlueprintReadOnly)
    UUnrealGuessLogSessionIdIndex* SessionId;

    void PostInitialize();

    /** Update function for unreal_guess_log table*/
    FTableAppliedDiff<FUnrealGuessLogType> Update(TArray<FWithBsatn<FUnrealGuessLogType>> InsertsRef, TArray<FWithBsatn<FUnrealGuessLogType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FUnrealGuessLogType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnUnrealGuessLogInsert,
        const FEventContext&, Context,
        const FUnrealGuessLogType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnUnrealGuessLogUpdate,
        const FEventContext&, Context,
        const FUnrealGuessLogType&, OldRow,
        const FUnrealGuessLogType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnUnrealGuessLogDelete,
        const FEventContext&, Context,
        const FUnrealGuessLogType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealGuessLogInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealGuessLogUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealGuessLogDelete OnDelete;

private:
    const FString TableName = TEXT("unreal_guess_log");

    TSharedPtr<UClientCache<FUnrealGuessLogType>> Data;
};
