// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/UnrealRoundResultType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "UnrealRoundResultTable.g.generated.h"

UCLASS(Blueprintable)
class CH_4_API UUnrealRoundResultIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FUnrealRoundResultType, uint64, FTableCache<FUnrealRoundResultType>> IdIndexHelper;

public:
    UUnrealRoundResultIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a UnrealRoundResult by their unique id.
     * @param Key The id to search for.
     * @return The found FUnrealRoundResultType, or a default-constructed FUnrealRoundResultType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FUnrealRoundResultType Find(uint64 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FUnrealRoundResultType>> InUnrealRoundResultCache)
    {
        IdIndexHelper.Cache = InUnrealRoundResultCache;
    }
};
/***/

UCLASS(Blueprintable)
class UUnrealRoundResultRoundIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FUnrealRoundResultType> Filter(const uint32& Round) const
    {
        TArray<FUnrealRoundResultType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<uint32>>(
            OutResults,
            TEXT("round"),
            MakeTuple(Round)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FUnrealRoundResultType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    // NOTE: Not exposed to Blueprint because some parameter types are not Blueprint-compatible
    void FilterRound(TArray<FUnrealRoundResultType>& OutResults, const uint32& Round)
    {
        OutResults = Filter(Round);
    }

    TSharedPtr<FTableCache<FUnrealRoundResultType>> LocalCache;
};

UCLASS(Blueprintable)
class UUnrealRoundResultSessionIdIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FUnrealRoundResultType> Filter(const FString& SessionId) const
    {
        TArray<FUnrealRoundResultType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<FString>>(
            OutResults,
            TEXT("session_id"),
            MakeTuple(SessionId)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FUnrealRoundResultType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    UFUNCTION(BlueprintCallable)
    void FilterSessionId(TArray<FUnrealRoundResultType>& OutResults, const FString& SessionId)
    {
        OutResults = Filter(SessionId);
    }

    TSharedPtr<FTableCache<FUnrealRoundResultType>> LocalCache;
};

UCLASS(BlueprintType)
class CH_4_API UUnrealRoundResultTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UUnrealRoundResultIdUniqueIndex* Id;

    UPROPERTY(BlueprintReadOnly)
    UUnrealRoundResultRoundIndex* Round;

    UPROPERTY(BlueprintReadOnly)
    UUnrealRoundResultSessionIdIndex* SessionId;

    void PostInitialize();

    /** Update function for unreal_round_result table*/
    FTableAppliedDiff<FUnrealRoundResultType> Update(TArray<FWithBsatn<FUnrealRoundResultType>> InsertsRef, TArray<FWithBsatn<FUnrealRoundResultType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FUnrealRoundResultType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnUnrealRoundResultInsert,
        const FEventContext&, Context,
        const FUnrealRoundResultType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnUnrealRoundResultUpdate,
        const FEventContext&, Context,
        const FUnrealRoundResultType&, OldRow,
        const FUnrealRoundResultType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnUnrealRoundResultDelete,
        const FEventContext&, Context,
        const FUnrealRoundResultType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealRoundResultInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealRoundResultUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealRoundResultDelete OnDelete;

private:
    const FString TableName = TEXT("unreal_round_result");

    TSharedPtr<UClientCache<FUnrealRoundResultType>> Data;
};
