// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/UnrealPlayerStatsType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "UnrealPlayerStatsTable.g.generated.h"

UCLASS(Blueprintable)
class CH_4_API UUnrealPlayerStatsPlayerNumberUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FUnrealPlayerStatsType, uint32, FTableCache<FUnrealPlayerStatsType>> PlayerNumberIndexHelper;

public:
    UUnrealPlayerStatsPlayerNumberUniqueIndex()
        // Initialize the helper with the specific unique index name
        : PlayerNumberIndexHelper("player_number") {
    }

    /**
     * Finds a UnrealPlayerStats by their unique playernumber.
     * @param Key The playernumber to search for.
     * @return The found FUnrealPlayerStatsType, or a default-constructed FUnrealPlayerStatsType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FUnrealPlayerStatsType Find(uint32 Key)
    {
        // Simply delegate the call to the internal helper
        return PlayerNumberIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FUnrealPlayerStatsType>> InUnrealPlayerStatsCache)
    {
        PlayerNumberIndexHelper.Cache = InUnrealPlayerStatsCache;
    }
};
/***/

UCLASS(BlueprintType)
class CH_4_API UUnrealPlayerStatsTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UUnrealPlayerStatsPlayerNumberUniqueIndex* PlayerNumber;

    void PostInitialize();

    /** Update function for unreal_player_stats table*/
    FTableAppliedDiff<FUnrealPlayerStatsType> Update(TArray<FWithBsatn<FUnrealPlayerStatsType>> InsertsRef, TArray<FWithBsatn<FUnrealPlayerStatsType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FUnrealPlayerStatsType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnUnrealPlayerStatsInsert,
        const FEventContext&, Context,
        const FUnrealPlayerStatsType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnUnrealPlayerStatsUpdate,
        const FEventContext&, Context,
        const FUnrealPlayerStatsType&, OldRow,
        const FUnrealPlayerStatsType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnUnrealPlayerStatsDelete,
        const FEventContext&, Context,
        const FUnrealPlayerStatsType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealPlayerStatsInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealPlayerStatsUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnUnrealPlayerStatsDelete OnDelete;

private:
    const FString TableName = TEXT("unreal_player_stats");

    TSharedPtr<UClientCache<FUnrealPlayerStatsType>> Data;
};
