// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameSecret = __t.object("GameSecret", {
  id: __t.u32(),
  answer: __t.string(),
});
export type GameSecret = __Infer<typeof GameSecret>;

export const GameState = __t.object("GameState", {
  id: __t.u32(),
  round: __t.u32(),
  status: __t.string(),
  winnerName: __t.option(__t.string()),
});
export type GameState = __Infer<typeof GameState>;

export const GuessResult = __t.object("GuessResult", {
  id: __t.u64(),
  round: __t.u32(),
  playerIdentity: __t.identity(),
  playerName: __t.string(),
  guess: __t.string(),
  strikes: __t.u32(),
  balls: __t.u32(),
  isOut: __t.bool(),
  attemptsLeft: __t.u32(),
  createdAt: __t.timestamp(),
});
export type GuessResult = __Infer<typeof GuessResult>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  attemptsLeft: __t.u32(),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

