// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Ch4OptionalUInt32.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FCh4OptionalUInt32
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool bHasValue = false;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Value = {};

    FCh4OptionalUInt32() = default;

    explicit FCh4OptionalUInt32(const uint32& InValue)
        : bHasValue(true), Value(InValue) {}

    bool IsSet() const { return bHasValue; }
    void Reset() { bHasValue = false; }

    FORCEINLINE bool operator==(const FCh4OptionalUInt32& Other) const
    {
        if (bHasValue != Other.bHasValue) return false;
        return !bHasValue || Value == Other.Value;
    }

    FORCEINLINE bool operator!=(const FCh4OptionalUInt32& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FCh4OptionalUInt32.
 * Hashes the HasValue flag and the Value if present.
 * @param Optional The FCh4OptionalUInt32 instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FCh4OptionalUInt32& Optional)
{
    uint32 Hash = GetTypeHash(Optional.bHasValue);
    if (Optional.bHasValue)
    {
        Hash = HashCombine(Hash, GetTypeHash(Optional.Value));
    }
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FCh4OptionalUInt32);

    UE_SPACETIMEDB_OPTIONAL(FCh4OptionalUInt32, bHasValue, Value);
}
