// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.0 (commit d220349adb7af7eefa810eb08a185609356b83f6).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Connection/Callback.h"
#include "Connection/DbConnectionBase.h"
#include "Connection/DbConnectionBuilder.h"
#include "Connection/Subscription.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Reducers/RecordUnrealGuess.g.h"
#include "ModuleBindings/Reducers/RecordUnrealRoundResult.g.h"
#include "ModuleBindings/Reducers/SetName.g.h"
#include "ModuleBindings/Reducers/StartNewRound.g.h"
#include "ModuleBindings/Reducers/SubmitGuess.g.h"
#include "ModuleBindings/Types/GameStateType.g.h"
#include "ModuleBindings/Types/GuessResultType.g.h"
#include "ModuleBindings/Types/PlayerType.g.h"
#include "ModuleBindings/Types/UnrealGuessLogType.g.h"
#include "ModuleBindings/Types/UnrealPlayerStatsType.g.h"
#include "ModuleBindings/Types/UnrealRoundResultType.g.h"
#include "QueryBuilder/query_builder.h"
#include "Types/Builtins.h"
#include "SpacetimeDBClient.g.generated.h"

// Forward declarations
class UDbConnection;
class URemoteTables;
class URemoteReducers;
class URemoteProcedures;
class USubscriptionBuilder;
class USubscriptionHandle;

/** Forward declaration for tables */
class UGameStateTable;
class UGuessResultTable;
class UPlayerTable;
class UUnrealGuessLogTable;
class UUnrealPlayerStatsTable;
class UUnrealRoundResultTable;
/***/

// Delegates using the generated connection type. These wrap the base
// delegates defined in the SDK so that projects can work directly with
// UDbConnection without manual casting in user code.
DECLARE_DYNAMIC_DELEGATE_ThreeParams(
	FOnConnectDelegate,
	UDbConnection*, Connection,
	FSpacetimeDBIdentity, Identity,
	const FString&, Token);

DECLARE_DYNAMIC_DELEGATE_TwoParams(
	FOnDisconnectDelegate,
	UDbConnection*, Connection,
	const FString&, Error);


// Context classes for event handling

USTRUCT(BlueprintType)
struct CH_4_API FContextBase
{
	GENERATED_BODY()

	FContextBase() : Db(nullptr), Reducers(nullptr), Procedures(nullptr), Conn(nullptr) {};
	FContextBase(UDbConnection* InConn);

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteTables* Db;

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteReducers* Reducers;

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteProcedures* Procedures;

	bool IsActive() const;
	void Disconnect();
	bool TryGetIdentity(FSpacetimeDBIdentity& OutIdentity) const;
	FSpacetimeDBConnectionId GetConnectionId() const;
	USubscriptionBuilder* SubscriptionBuilder();

protected:
	UPROPERTY()
	UDbConnection* Conn;

};

UCLASS()
class CH_4_API UContextBaseBpLib : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

private:
	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static URemoteTables* GetDb(const FContextBase& Ctx) { return Ctx.Db; }

	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static URemoteReducers* GetReducers(const FContextBase& Ctx) { return Ctx.Reducers; }

	static URemoteProcedures* GetProcedures(const FContextBase& Ctx) { return Ctx.Procedures; }

	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static bool IsActive(const FContextBase& Ctx) { return Ctx.IsActive(); }
};

UENUM(BlueprintType, Category = "SpacetimeDB")
enum class EReducerTag : uint8
{
    RecordUnrealGuess,
    RecordUnrealRoundResult,
    SetName,
    StartNewRound,
    SubmitGuess
};

USTRUCT(BlueprintType)
struct CH_4_API FReducer
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
    EReducerTag Tag = static_cast<EReducerTag>(0);

    TVariant<FRecordUnrealGuessArgs, FRecordUnrealRoundResultArgs, FSetNameArgs, FStartNewRoundArgs, FSubmitGuessArgs> Data;

    // Optional metadata
    UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
    FString ReducerName;
    uint32 ReducerId = 0;
    uint32 RequestId = 0;

    static FReducer RecordUnrealGuess(const FRecordUnrealGuessArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::RecordUnrealGuess;
        Out.Data.Set<FRecordUnrealGuessArgs>(Value);
        Out.ReducerName = TEXT("record_unreal_guess");
        return Out;
    }

    FORCEINLINE bool IsRecordUnrealGuess() const { return Tag == EReducerTag::RecordUnrealGuess; }
    FORCEINLINE FRecordUnrealGuessArgs GetAsRecordUnrealGuess() const
    {
        ensureMsgf(IsRecordUnrealGuess(), TEXT("Reducer does not hold RecordUnrealGuess!"));
        return Data.Get<FRecordUnrealGuessArgs>();
    }

    static FReducer RecordUnrealRoundResult(const FRecordUnrealRoundResultArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::RecordUnrealRoundResult;
        Out.Data.Set<FRecordUnrealRoundResultArgs>(Value);
        Out.ReducerName = TEXT("record_unreal_round_result");
        return Out;
    }

    FORCEINLINE bool IsRecordUnrealRoundResult() const { return Tag == EReducerTag::RecordUnrealRoundResult; }
    FORCEINLINE FRecordUnrealRoundResultArgs GetAsRecordUnrealRoundResult() const
    {
        ensureMsgf(IsRecordUnrealRoundResult(), TEXT("Reducer does not hold RecordUnrealRoundResult!"));
        return Data.Get<FRecordUnrealRoundResultArgs>();
    }

    static FReducer SetName(const FSetNameArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::SetName;
        Out.Data.Set<FSetNameArgs>(Value);
        Out.ReducerName = TEXT("set_name");
        return Out;
    }

    FORCEINLINE bool IsSetName() const { return Tag == EReducerTag::SetName; }
    FORCEINLINE FSetNameArgs GetAsSetName() const
    {
        ensureMsgf(IsSetName(), TEXT("Reducer does not hold SetName!"));
        return Data.Get<FSetNameArgs>();
    }

    static FReducer StartNewRound(const FStartNewRoundArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::StartNewRound;
        Out.Data.Set<FStartNewRoundArgs>(Value);
        Out.ReducerName = TEXT("start_new_round");
        return Out;
    }

    FORCEINLINE bool IsStartNewRound() const { return Tag == EReducerTag::StartNewRound; }
    FORCEINLINE FStartNewRoundArgs GetAsStartNewRound() const
    {
        ensureMsgf(IsStartNewRound(), TEXT("Reducer does not hold StartNewRound!"));
        return Data.Get<FStartNewRoundArgs>();
    }

    static FReducer SubmitGuess(const FSubmitGuessArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::SubmitGuess;
        Out.Data.Set<FSubmitGuessArgs>(Value);
        Out.ReducerName = TEXT("submit_guess");
        return Out;
    }

    FORCEINLINE bool IsSubmitGuess() const { return Tag == EReducerTag::SubmitGuess; }
    FORCEINLINE FSubmitGuessArgs GetAsSubmitGuess() const
    {
        ensureMsgf(IsSubmitGuess(), TEXT("Reducer does not hold SubmitGuess!"));
        return Data.Get<FSubmitGuessArgs>();
    }

    FORCEINLINE bool operator==(const FReducer& Other) const
    {
        if (Tag != Other.Tag || ReducerId != Other.ReducerId || RequestId != Other.RequestId || ReducerName != Other.ReducerName) return false;
        switch (Tag)
        {
        case EReducerTag::RecordUnrealGuess:
            return GetAsRecordUnrealGuess() == Other.GetAsRecordUnrealGuess();
        case EReducerTag::RecordUnrealRoundResult:
            return GetAsRecordUnrealRoundResult() == Other.GetAsRecordUnrealRoundResult();
        case EReducerTag::SetName:
            return GetAsSetName() == Other.GetAsSetName();
        case EReducerTag::StartNewRound:
            return GetAsStartNewRound() == Other.GetAsStartNewRound();
        case EReducerTag::SubmitGuess:
            return GetAsSubmitGuess() == Other.GetAsSubmitGuess();
        default: return false;
        }
    }
    FORCEINLINE bool operator!=(const FReducer& Other) const { return !(*this == Other); }
};

UCLASS()
class CH_4_API UReducerBpLib : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

private:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer RecordUnrealGuess(const FRecordUnrealGuessArgs& Value) {
        return FReducer::RecordUnrealGuess(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsRecordUnrealGuess(const FReducer& Reducer) { return Reducer.IsRecordUnrealGuess(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FRecordUnrealGuessArgs GetAsRecordUnrealGuess(const FReducer& Reducer) {
        return Reducer.GetAsRecordUnrealGuess();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer RecordUnrealRoundResult(const FRecordUnrealRoundResultArgs& Value) {
        return FReducer::RecordUnrealRoundResult(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsRecordUnrealRoundResult(const FReducer& Reducer) { return Reducer.IsRecordUnrealRoundResult(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FRecordUnrealRoundResultArgs GetAsRecordUnrealRoundResult(const FReducer& Reducer) {
        return Reducer.GetAsRecordUnrealRoundResult();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer SetName(const FSetNameArgs& Value) {
        return FReducer::SetName(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsSetName(const FReducer& Reducer) { return Reducer.IsSetName(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FSetNameArgs GetAsSetName(const FReducer& Reducer) {
        return Reducer.GetAsSetName();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer StartNewRound(const FStartNewRoundArgs& Value) {
        return FReducer::StartNewRound(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsStartNewRound(const FReducer& Reducer) { return Reducer.IsStartNewRound(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FStartNewRoundArgs GetAsStartNewRound(const FReducer& Reducer) {
        return Reducer.GetAsStartNewRound();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer SubmitGuess(const FSubmitGuessArgs& Value) {
        return FReducer::SubmitGuess(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsSubmitGuess(const FReducer& Reducer) { return Reducer.IsSubmitGuess(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FSubmitGuessArgs GetAsSubmitGuess(const FReducer& Reducer) {
        return Reducer.GetAsSubmitGuess();
    }
};

/** Metadata describing a reducer run. */
USTRUCT(BlueprintType)
struct CH_4_API FCh4ReducerEvent
{
	GENERATED_BODY()

	/** Timestamp for when the reducer executed */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimestamp Timestamp;

	/** Result status of the reducer */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBStatus Status;

	/** Identity that initiated the call */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBIdentity CallerIdentity;

	/** Connection ID for the caller */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBConnectionId CallerConnectionId;

	/** Energy consumed while executing */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FEnergyQuantaType EnergyConsumed;

	/** Detailed call information */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FReducer Reducer;

	FORCEINLINE bool operator==(const FCh4ReducerEvent& Other) const
	{
		return Status == Other.Status && Timestamp == Other.Timestamp && CallerIdentity == Other.CallerIdentity &&
			CallerConnectionId == Other.CallerConnectionId && EnergyConsumed == Other.EnergyConsumed &&
			Reducer == Other.Reducer;
	}

	FORCEINLINE bool operator!=(const FCh4ReducerEvent& Other) const
	{
		return !(*this == Other);
	}
};

// No procedures defined in this module.
/** Metadata describing a procedure run. */
USTRUCT(BlueprintType)
struct CH_4_API FCh4ProcedureEvent
{
	GENERATED_BODY()

	/** Timestamp for when the procedure executed */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimestamp Timestamp;

	/** Result status of the procedure */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBProcedureStatus Status;

	/** Identity that initiated the call */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimeDuration TotalHostExecutionDuration;

	FCh4ProcedureEvent() {
	}
	FCh4ProcedureEvent(FProcedureEvent Event) {
		Timestamp = Event.Timestamp;
		Status = FSpacetimeDBProcedureStatus::FromStatus(Event.Status);
		TotalHostExecutionDuration = Event.TotalHostExecutionDuration;
	}
	FORCEINLINE bool operator==(const FCh4ProcedureEvent& Other) const
	{
		return Status == Other.Status && Timestamp == Other.Timestamp &&
			TotalHostExecutionDuration == Other.TotalHostExecutionDuration;
	}

	FORCEINLINE bool operator!=(const FCh4ProcedureEvent& Other) const
	{
		return !(*this == Other);
	}
};

/** Represents event with variant message data. */
USTRUCT(BlueprintType)
struct CH_4_API FCh4Event
{
	GENERATED_BODY()

	/** Tagged union holding reducer call, unit events, or error string */
	TVariant<FReducer, FSpacetimeDBUnit, FString> MessageData;

	/** Type tag indicating what this event represents */
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	ESpacetimeDBEventTag Tag = ESpacetimeDBEventTag::UnknownTransaction;

	/** === Static factory methods ===*/
	static FCh4Event Reducer(const FReducer& Value)
	{
		FCh4Event Obj;
		Obj.Tag = ESpacetimeDBEventTag::Reducer;
		Obj.MessageData.Set<FReducer>(Value);
		return Obj;
	}

	static FCh4Event SubscribeApplied(const FSpacetimeDBUnit& Value)
	{
		FCh4Event Obj;
		Obj.Tag = ESpacetimeDBEventTag::SubscribeApplied;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FCh4Event UnsubscribeApplied(const FSpacetimeDBUnit& Value)
	{
		FCh4Event Obj;
		Obj.Tag = ESpacetimeDBEventTag::UnsubscribeApplied;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FCh4Event Disconnected(const FSpacetimeDBUnit& Value)
	{
		FCh4Event Obj;
		Obj.Tag = ESpacetimeDBEventTag::Disconnected;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FCh4Event Transaction(const FSpacetimeDBUnit& Value)
	{
		FCh4Event Obj;
		Obj.Tag = ESpacetimeDBEventTag::Transaction;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FCh4Event SubscribeError(const FString& Value)
	{
		FCh4Event Obj;
		Obj.Tag = ESpacetimeDBEventTag::SubscribeError;
		Obj.MessageData.Set<FString>(Value);
		return Obj;
	}

	static FCh4Event UnknownTransaction(const FSpacetimeDBUnit& Value)
	{
		FCh4Event Obj;
		Obj.Tag = ESpacetimeDBEventTag::UnknownTransaction;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	FORCEINLINE bool IsReducer() const { return Tag == ESpacetimeDBEventTag::Reducer; }
	FORCEINLINE FReducer GetAsReducer() const
	{
		ensureMsgf(IsReducer(), TEXT("MessageData does not hold Reducer!"));
		return MessageData.Get<FReducer>();
	}

	FORCEINLINE bool IsSubscribeApplied() const { return Tag == ESpacetimeDBEventTag::SubscribeApplied; }
	FORCEINLINE FSpacetimeDBUnit GetAsSubscribeApplied() const
	{
		ensureMsgf(IsSubscribeApplied(), TEXT("MessageData does not hold SubscribeApplied!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsUnsubscribeApplied() const { return Tag == ESpacetimeDBEventTag::UnsubscribeApplied; }
	FORCEINLINE FSpacetimeDBUnit GetAsUnsubscribeApplied() const
	{
		ensureMsgf(IsUnsubscribeApplied(), TEXT("MessageData does not hold UnsubscribeApplied!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsDisconnected() const { return Tag == ESpacetimeDBEventTag::Disconnected; }
	FORCEINLINE FSpacetimeDBUnit GetAsDisconnected() const
	{
		ensureMsgf(IsDisconnected(), TEXT("MessageData does not hold Disconnected!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsTransaction() const { return Tag == ESpacetimeDBEventTag::Transaction; }
	FORCEINLINE FSpacetimeDBUnit GetAsTransaction() const
	{
		ensureMsgf(IsTransaction(), TEXT("MessageData does not hold Transaction!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsSubscribeError() const { return Tag == ESpacetimeDBEventTag::SubscribeError; }
	FORCEINLINE FString GetAsSubscribeError() const
	{
		ensureMsgf(IsSubscribeError(), TEXT("MessageData does not hold SubscribeError!"));
		return MessageData.Get<FString>();
	}

	FORCEINLINE bool IsUnknownTransaction() const { return Tag == ESpacetimeDBEventTag::UnknownTransaction; }
	FORCEINLINE FSpacetimeDBUnit GetAsUnknownTransaction() const
	{
		ensureMsgf(IsUnknownTransaction(), TEXT("MessageData does not hold UnknownTransaction!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool operator==(const FCh4Event& Other) const
	{
		if (Tag != Other.Tag) return false;
		switch (Tag)
		{
		case ESpacetimeDBEventTag::Reducer: return GetAsReducer() == Other.GetAsReducer();
		case ESpacetimeDBEventTag::SubscribeApplied: return GetAsSubscribeApplied() == Other.GetAsSubscribeApplied();
		case ESpacetimeDBEventTag::UnsubscribeApplied: return GetAsUnsubscribeApplied() == Other.GetAsUnsubscribeApplied();
		case ESpacetimeDBEventTag::Disconnected: return GetAsDisconnected() == Other.GetAsDisconnected();
		case ESpacetimeDBEventTag::Transaction: return GetAsTransaction() == Other.GetAsTransaction();
		case ESpacetimeDBEventTag::SubscribeError: return GetAsSubscribeError() == Other.GetAsSubscribeError();
		case ESpacetimeDBEventTag::UnknownTransaction: return GetAsUnknownTransaction() == Other.GetAsUnknownTransaction();
		default: return false;
		}
	}

	FORCEINLINE bool operator!=(const FCh4Event& Other) const
	{
		return !(*this == Other);
	}
};

UCLASS()
class CH_4_API UCh4EventBpLib : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

private:
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Ch4Event")
    static FCh4Event Reducer(const FReducer& InValue)
    {
        return FCh4Event::Reducer(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Ch4Event")
    static FCh4Event SubscribeApplied(const FSpacetimeDBUnit& InValue)
    {
        return FCh4Event::SubscribeApplied(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Ch4Event")
    static FCh4Event UnsubscribeApplied(const FSpacetimeDBUnit& InValue)
    {
        return FCh4Event::UnsubscribeApplied(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Ch4Event")
    static FCh4Event Disconnected(const FSpacetimeDBUnit& InValue)
    {
        return FCh4Event::Disconnected(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Ch4Event")
    static FCh4Event Transaction(const FSpacetimeDBUnit& InValue)
    {
        return FCh4Event::Transaction(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Ch4Event")
    static FCh4Event SubscribeError(const FString& InValue)
    {
        return FCh4Event::SubscribeError(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Ch4Event")
    static FCh4Event UnknownTransaction(const FSpacetimeDBUnit& InValue)
    {
        return FCh4Event::UnknownTransaction(InValue);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static bool IsReducer(const FCh4Event& Event) { return Event.IsReducer(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static bool IsSubscribeApplied(const FCh4Event& Event) { return Event.IsSubscribeApplied(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static bool IsUnsubscribeApplied(const FCh4Event& Event) { return Event.IsUnsubscribeApplied(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static bool IsDisconnected(const FCh4Event& Event) { return Event.IsDisconnected(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static bool IsTransaction(const FCh4Event& Event) { return Event.IsTransaction(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static bool IsSubscribeError(const FCh4Event& Event) { return Event.IsSubscribeError(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static bool IsUnknownTransaction(const FCh4Event& Event) { return Event.IsUnknownTransaction(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static FReducer GetAsReducer(const FCh4Event& Event)
    {
        return Event.GetAsReducer();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static FSpacetimeDBUnit GetAsSubscribeApplied(const FCh4Event& Event)
    {
        return Event.GetAsSubscribeApplied();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static FSpacetimeDBUnit GetAsUnsubscribeApplied(const FCh4Event& Event)
    {
        return Event.GetAsUnsubscribeApplied();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static FSpacetimeDBUnit GetAsDisconnected(const FCh4Event& Event)
    {
        return Event.GetAsDisconnected();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static FSpacetimeDBUnit GetAsTransaction(const FCh4Event& Event)
    {
        return Event.GetAsTransaction();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static FString GetAsSubscribeError(const FCh4Event& Event)
    {
        return Event.GetAsSubscribeError();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Ch4Event")
    static FSpacetimeDBUnit GetAsUnknownTransaction(const FCh4Event& Event)
    {
        return Event.GetAsUnknownTransaction();
    }

};


USTRUCT(BlueprintType)
struct CH_4_API FEventContext : public FContextBase
{
	GENERATED_BODY()

	FEventContext() = default;
	FEventContext(UDbConnection* InConn, const FCh4Event& InEvent) : FContextBase(InConn), Event(InEvent) {}

	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	FCh4Event Event;
};

USTRUCT(BlueprintType)
struct CH_4_API FReducerEventContext : public FContextBase
{
	GENERATED_BODY()

	FReducerEventContext() = default;
	FReducerEventContext(UDbConnection* InConn, FCh4ReducerEvent InEvent) : FContextBase(InConn), Event(InEvent) {}
	
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB") 
	FCh4ReducerEvent Event;
};

USTRUCT(BlueprintType)
struct CH_4_API FProcedureEventContext : public FContextBase
{
	GENERATED_BODY()

	FProcedureEventContext() = default;
	FProcedureEventContext(UDbConnection* InConn, FCh4ProcedureEvent InEvent) : FContextBase(InConn), Event(InEvent) {}
	
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB") 
	FCh4ProcedureEvent Event;
};

USTRUCT(BlueprintType)
struct CH_4_API FErrorContext : public FContextBase
{
	GENERATED_BODY()

	FErrorContext() = default;
	FErrorContext(UDbConnection* InConn, const FString& InError) : FContextBase(InConn), Error(InError) {}

	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	FString Error;

};

USTRUCT(BlueprintType)
struct CH_4_API FSubscriptionEventContext : public FContextBase
{
	GENERATED_BODY()

	FSubscriptionEventContext() = default;
	FSubscriptionEventContext(UDbConnection* InConn) : FContextBase(InConn) {}

};

DECLARE_DYNAMIC_DELEGATE_OneParam(
	FOnSubscriptionApplied,
	FSubscriptionEventContext, Context);

DECLARE_DYNAMIC_DELEGATE_OneParam(
	FOnSubscriptionError,
	FErrorContext, Context);

// RemoteTables class
UCLASS(BlueprintType)
class CH_4_API URemoteTables : public UObject
{
    GENERATED_BODY()

public:
    void Initialize();

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UGameStateTable* GameState;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UGuessResultTable* GuessResult;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UPlayerTable* Player;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UUnrealGuessLogTable* UnrealGuessLog;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UUnrealPlayerStatsTable* UnrealPlayerStats;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UUnrealRoundResultTable* UnrealRoundResult;

};

// RemoteReducers class
UCLASS(BlueprintType)
class CH_4_API URemoteReducers : public UObject
{
    GENERATED_BODY()

public:

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_EightParams(
        FRecordUnrealGuessHandler,
        const FReducerEventContext&, Context,
        const FString&, SessionId,
        uint32, Round,
        uint32, PlayerNumber,
        const FString&, Guess,
        uint32, Strikes,
        uint32, Balls,
        uint32, AttemptNumber
    );
    // NOTE: Not exposed to Blueprint because uint32, uint32, uint32, uint32, uint32 types are not Blueprint-compatible
    FRecordUnrealGuessHandler OnRecordUnrealGuess;

    // NOTE: Not exposed to Blueprint because uint32, uint32, uint32, uint32, uint32 types are not Blueprint-compatible
    void RecordUnrealGuess(const FString& SessionId, const uint32 Round, const uint32 PlayerNumber, const FString& Guess, const uint32 Strikes, const uint32 Balls, const uint32 AttemptNumber);

    bool InvokeRecordUnrealGuess(const FReducerEventContext& Context, const URecordUnrealGuessReducer* Args);
    bool InvokeRecordUnrealGuessWithArgs(const FReducerEventContext& Context, const FRecordUnrealGuessArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams(
        FRecordUnrealRoundResultHandler,
        const FReducerEventContext&, Context,
        const FString&, SessionId,
        uint32, Round,
        const FString&, Answer,
        const FString&, Status,
        uint32, WinnerPlayerNumber
    );
    // NOTE: Not exposed to Blueprint because uint32, uint32 types are not Blueprint-compatible
    FRecordUnrealRoundResultHandler OnRecordUnrealRoundResult;

    // NOTE: Not exposed to Blueprint because uint32, uint32 types are not Blueprint-compatible
    void RecordUnrealRoundResult(const FString& SessionId, const uint32 Round, const FString& Answer, const FString& Status, const uint32 WinnerPlayerNumber);

    bool InvokeRecordUnrealRoundResult(const FReducerEventContext& Context, const URecordUnrealRoundResultReducer* Args);
    bool InvokeRecordUnrealRoundResultWithArgs(const FReducerEventContext& Context, const FRecordUnrealRoundResultArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FSetNameHandler,
        const FReducerEventContext&, Context,
        const FString&, Name
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FSetNameHandler OnSetName;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void SetName(const FString& Name);

    bool InvokeSetName(const FReducerEventContext& Context, const USetNameReducer* Args);
    bool InvokeSetNameWithArgs(const FReducerEventContext& Context, const FSetNameArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
        FStartNewRoundHandler,
        const FReducerEventContext&, Context
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FStartNewRoundHandler OnStartNewRound;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void StartNewRound();

    bool InvokeStartNewRound(const FReducerEventContext& Context, const UStartNewRoundReducer* Args);
    bool InvokeStartNewRoundWithArgs(const FReducerEventContext& Context, const FStartNewRoundArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FSubmitGuessHandler,
        const FReducerEventContext&, Context,
        const FString&, Guess
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FSubmitGuessHandler OnSubmitGuess;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void SubmitGuess(const FString& Guess);

    bool InvokeSubmitGuess(const FReducerEventContext& Context, const USubmitGuessReducer* Args);
    bool InvokeSubmitGuessWithArgs(const FReducerEventContext& Context, const FSubmitGuessArgs& Args);

    // Internal error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FInternalOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);
    FInternalOnUnhandledReducerError InternalOnUnhandledReducerError;

private:

    friend UDbConnection;

    UPROPERTY()
    class UDbConnection* Conn;
};

// RemoteProcedures class
UCLASS(BlueprintType)
class CH_4_API URemoteProcedures : public UObject
{
    GENERATED_BODY()

public:

    // Internal error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FInternalOnUnhandledProcedureError, const FProcedureEventContext&, Context, const FString&, Error);
    FInternalOnUnhandledProcedureError InternalOnUnhandledProcedureError;

private:

    friend UDbConnection;

    UPROPERTY()
    class UDbConnection* Conn;
};

// QueryBuilder types
struct CH_4_API FGameStateCols;
struct CH_4_API FGameStateIxCols;
struct CH_4_API FGuessResultCols;
struct CH_4_API FGuessResultIxCols;
struct CH_4_API FPlayerCols;
struct CH_4_API FPlayerIxCols;
struct CH_4_API FUnrealGuessLogCols;
struct CH_4_API FUnrealGuessLogIxCols;
struct CH_4_API FUnrealPlayerStatsCols;
struct CH_4_API FUnrealPlayerStatsIxCols;
struct CH_4_API FUnrealRoundResultCols;
struct CH_4_API FUnrealRoundResultIxCols;

struct CH_4_API FGameStateCols
{
    explicit FGameStateCols(const char* TableName)
        : Id(TableName, "id"), Round(TableName, "round"), Status(TableName, "status"), WinnerName(TableName, "winner_name") {}

    ::SpacetimeDB::query_builder::Col<FGameStateType, uint32> Id;
    ::SpacetimeDB::query_builder::Col<FGameStateType, uint32> Round;
    ::SpacetimeDB::query_builder::Col<FGameStateType, FString> Status;
    ::SpacetimeDB::query_builder::Col<FGameStateType, FCh4OptionalString> WinnerName;
};

struct CH_4_API FGameStateIxCols
{
    explicit FGameStateIxCols(const char* TableName)
        : Id(TableName, "id") {}

    ::SpacetimeDB::query_builder::IxCol<FGameStateType, uint32> Id;
};

namespace SpacetimeDB::query_builder
{
    template<>
    struct CanBeLookupTable<Table<FGameStateType, FGameStateCols, FGameStateIxCols>> : std::true_type {};
}

struct CH_4_API FGuessResultCols
{
    explicit FGuessResultCols(const char* TableName)
        : Id(TableName, "id"), Round(TableName, "round"), PlayerIdentity(TableName, "player_identity"), PlayerName(TableName, "player_name"), Guess(TableName, "guess"), Strikes(TableName, "strikes"), Balls(TableName, "balls"), IsOut(TableName, "is_out"), AttemptsLeft(TableName, "attempts_left"), CreatedAt(TableName, "created_at") {}

    ::SpacetimeDB::query_builder::Col<FGuessResultType, uint64> Id;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, uint32> Round;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, FSpacetimeDBIdentity> PlayerIdentity;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, FString> PlayerName;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, FString> Guess;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, uint32> Strikes;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, uint32> Balls;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, bool> IsOut;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, uint32> AttemptsLeft;
    ::SpacetimeDB::query_builder::Col<FGuessResultType, FSpacetimeDBTimestamp> CreatedAt;
};

struct CH_4_API FGuessResultIxCols
{
    explicit FGuessResultIxCols(const char* TableName)
        : Id(TableName, "id"), Round(TableName, "round") {}

    ::SpacetimeDB::query_builder::IxCol<FGuessResultType, uint64> Id;
    ::SpacetimeDB::query_builder::IxCol<FGuessResultType, uint32> Round;
};

namespace SpacetimeDB::query_builder
{
    template<>
    struct CanBeLookupTable<Table<FGuessResultType, FGuessResultCols, FGuessResultIxCols>> : std::true_type {};
}

struct CH_4_API FPlayerCols
{
    explicit FPlayerCols(const char* TableName)
        : Identity(TableName, "identity"), Name(TableName, "name"), AttemptsLeft(TableName, "attempts_left"), Online(TableName, "online") {}

    ::SpacetimeDB::query_builder::Col<FPlayerType, FSpacetimeDBIdentity> Identity;
    ::SpacetimeDB::query_builder::Col<FPlayerType, FString> Name;
    ::SpacetimeDB::query_builder::Col<FPlayerType, uint32> AttemptsLeft;
    ::SpacetimeDB::query_builder::Col<FPlayerType, bool> Online;
};

struct CH_4_API FPlayerIxCols
{
    explicit FPlayerIxCols(const char* TableName)
        : Identity(TableName, "identity") {}

    ::SpacetimeDB::query_builder::IxCol<FPlayerType, FSpacetimeDBIdentity> Identity;
};

namespace SpacetimeDB::query_builder
{
    template<>
    struct CanBeLookupTable<Table<FPlayerType, FPlayerCols, FPlayerIxCols>> : std::true_type {};
}

struct CH_4_API FUnrealGuessLogCols
{
    explicit FUnrealGuessLogCols(const char* TableName)
        : Id(TableName, "id"), SessionId(TableName, "session_id"), Round(TableName, "round"), PlayerNumber(TableName, "player_number"), Guess(TableName, "guess"), Strikes(TableName, "strikes"), Balls(TableName, "balls"), IsOut(TableName, "is_out"), AttemptNumber(TableName, "attempt_number"), CreatedAt(TableName, "created_at") {}

    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, uint64> Id;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, FString> SessionId;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, uint32> Round;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, uint32> PlayerNumber;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, FString> Guess;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, uint32> Strikes;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, uint32> Balls;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, bool> IsOut;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, uint32> AttemptNumber;
    ::SpacetimeDB::query_builder::Col<FUnrealGuessLogType, FSpacetimeDBTimestamp> CreatedAt;
};

struct CH_4_API FUnrealGuessLogIxCols
{
    explicit FUnrealGuessLogIxCols(const char* TableName)
        : Id(TableName, "id"), SessionId(TableName, "session_id"), Round(TableName, "round"), PlayerNumber(TableName, "player_number") {}

    ::SpacetimeDB::query_builder::IxCol<FUnrealGuessLogType, uint64> Id;
    ::SpacetimeDB::query_builder::IxCol<FUnrealGuessLogType, FString> SessionId;
    ::SpacetimeDB::query_builder::IxCol<FUnrealGuessLogType, uint32> Round;
    ::SpacetimeDB::query_builder::IxCol<FUnrealGuessLogType, uint32> PlayerNumber;
};

namespace SpacetimeDB::query_builder
{
    template<>
    struct CanBeLookupTable<Table<FUnrealGuessLogType, FUnrealGuessLogCols, FUnrealGuessLogIxCols>> : std::true_type {};
}

struct CH_4_API FUnrealPlayerStatsCols
{
    explicit FUnrealPlayerStatsCols(const char* TableName)
        : PlayerNumber(TableName, "player_number"), Wins(TableName, "wins") {}

    ::SpacetimeDB::query_builder::Col<FUnrealPlayerStatsType, uint32> PlayerNumber;
    ::SpacetimeDB::query_builder::Col<FUnrealPlayerStatsType, uint32> Wins;
};

struct CH_4_API FUnrealPlayerStatsIxCols
{
    explicit FUnrealPlayerStatsIxCols(const char* TableName)
        : PlayerNumber(TableName, "player_number") {}

    ::SpacetimeDB::query_builder::IxCol<FUnrealPlayerStatsType, uint32> PlayerNumber;
};

namespace SpacetimeDB::query_builder
{
    template<>
    struct CanBeLookupTable<Table<FUnrealPlayerStatsType, FUnrealPlayerStatsCols, FUnrealPlayerStatsIxCols>> : std::true_type {};
}

struct CH_4_API FUnrealRoundResultCols
{
    explicit FUnrealRoundResultCols(const char* TableName)
        : Id(TableName, "id"), SessionId(TableName, "session_id"), Round(TableName, "round"), Answer(TableName, "answer"), Status(TableName, "status"), WinnerPlayerNumber(TableName, "winner_player_number"), EndedAt(TableName, "ended_at") {}

    ::SpacetimeDB::query_builder::Col<FUnrealRoundResultType, uint64> Id;
    ::SpacetimeDB::query_builder::Col<FUnrealRoundResultType, FString> SessionId;
    ::SpacetimeDB::query_builder::Col<FUnrealRoundResultType, uint32> Round;
    ::SpacetimeDB::query_builder::Col<FUnrealRoundResultType, FString> Answer;
    ::SpacetimeDB::query_builder::Col<FUnrealRoundResultType, FString> Status;
    ::SpacetimeDB::query_builder::Col<FUnrealRoundResultType, FCh4OptionalUInt32> WinnerPlayerNumber;
    ::SpacetimeDB::query_builder::Col<FUnrealRoundResultType, FSpacetimeDBTimestamp> EndedAt;
};

struct CH_4_API FUnrealRoundResultIxCols
{
    explicit FUnrealRoundResultIxCols(const char* TableName)
        : Id(TableName, "id"), SessionId(TableName, "session_id"), Round(TableName, "round") {}

    ::SpacetimeDB::query_builder::IxCol<FUnrealRoundResultType, uint64> Id;
    ::SpacetimeDB::query_builder::IxCol<FUnrealRoundResultType, FString> SessionId;
    ::SpacetimeDB::query_builder::IxCol<FUnrealRoundResultType, uint32> Round;
};

namespace SpacetimeDB::query_builder
{
    template<>
    struct CanBeLookupTable<Table<FUnrealRoundResultType, FUnrealRoundResultCols, FUnrealRoundResultIxCols>> : std::true_type {};
}

struct CH_4_API FFrom
{
    [[nodiscard]] ::SpacetimeDB::query_builder::Table<FGameStateType, FGameStateCols, FGameStateIxCols> GameState() const { return ::SpacetimeDB::query_builder::Table<FGameStateType, FGameStateCols, FGameStateIxCols>("game_state", FGameStateCols("game_state"), FGameStateIxCols("game_state")); }
    [[nodiscard]] ::SpacetimeDB::query_builder::Table<FGuessResultType, FGuessResultCols, FGuessResultIxCols> GuessResult() const { return ::SpacetimeDB::query_builder::Table<FGuessResultType, FGuessResultCols, FGuessResultIxCols>("guess_result", FGuessResultCols("guess_result"), FGuessResultIxCols("guess_result")); }
    [[nodiscard]] ::SpacetimeDB::query_builder::Table<FPlayerType, FPlayerCols, FPlayerIxCols> Player() const { return ::SpacetimeDB::query_builder::Table<FPlayerType, FPlayerCols, FPlayerIxCols>("player", FPlayerCols("player"), FPlayerIxCols("player")); }
    [[nodiscard]] ::SpacetimeDB::query_builder::Table<FUnrealGuessLogType, FUnrealGuessLogCols, FUnrealGuessLogIxCols> UnrealGuessLog() const { return ::SpacetimeDB::query_builder::Table<FUnrealGuessLogType, FUnrealGuessLogCols, FUnrealGuessLogIxCols>("unreal_guess_log", FUnrealGuessLogCols("unreal_guess_log"), FUnrealGuessLogIxCols("unreal_guess_log")); }
    [[nodiscard]] ::SpacetimeDB::query_builder::Table<FUnrealPlayerStatsType, FUnrealPlayerStatsCols, FUnrealPlayerStatsIxCols> UnrealPlayerStats() const { return ::SpacetimeDB::query_builder::Table<FUnrealPlayerStatsType, FUnrealPlayerStatsCols, FUnrealPlayerStatsIxCols>("unreal_player_stats", FUnrealPlayerStatsCols("unreal_player_stats"), FUnrealPlayerStatsIxCols("unreal_player_stats")); }
    [[nodiscard]] ::SpacetimeDB::query_builder::Table<FUnrealRoundResultType, FUnrealRoundResultCols, FUnrealRoundResultIxCols> UnrealRoundResult() const { return ::SpacetimeDB::query_builder::Table<FUnrealRoundResultType, FUnrealRoundResultCols, FUnrealRoundResultIxCols>("unreal_round_result", FUnrealRoundResultCols("unreal_round_result"), FUnrealRoundResultIxCols("unreal_round_result")); }
};

struct CH_4_API FQueryBuilder
{
    FFrom From;

    static TArray<FString> AllTablesSqlQueries()
    {
        TArray<FString> Sql;
        Sql.Add(FString(UTF8_TO_TCHAR(FQueryBuilder().From.GameState().into_sql().c_str())));
        Sql.Add(FString(UTF8_TO_TCHAR(FQueryBuilder().From.GuessResult().into_sql().c_str())));
        Sql.Add(FString(UTF8_TO_TCHAR(FQueryBuilder().From.Player().into_sql().c_str())));
        Sql.Add(FString(UTF8_TO_TCHAR(FQueryBuilder().From.UnrealGuessLog().into_sql().c_str())));
        Sql.Add(FString(UTF8_TO_TCHAR(FQueryBuilder().From.UnrealPlayerStats().into_sql().c_str())));
        Sql.Add(FString(UTF8_TO_TCHAR(FQueryBuilder().From.UnrealRoundResult().into_sql().c_str())));
        return Sql;
    }
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintQuery
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintPredicate
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FGameStateQuery
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FGuessResultQuery
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FPlayerQuery
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FUnrealGuessLogQuery
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FUnrealPlayerStatsQuery
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FUnrealRoundResultQuery
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString Sql;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintBoolColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintUInt8Column
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintInt32Column
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintInt64Column
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintFloatColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintDoubleColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintStringColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintIdentityColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintConnectionIdColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintTimestampColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

USTRUCT(BlueprintType)
struct CH_4_API FBlueprintUuidColumn
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ResultSourceName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB|Queries")
    FString ColumnName;
};

UCLASS(BlueprintType)
class CH_4_API UQueryBuilderBlueprintLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

public:

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GameState", meta=(DisplayName="From GameState"))
    static FGameStateQuery FromGameState()
    {
        FGameStateQuery Query;
        Query.Sql = FString(UTF8_TO_TCHAR(FQueryBuilder().From.GameState().into_sql().c_str()));
        Query.ResultSourceName = TEXT("game_state");
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GameState", meta=(DisplayName="To Query", BlueprintAutocast))
    static FBlueprintQuery Conv_GameStateQueryToBlueprintQuery(const FGameStateQuery& Query)
    {
        FBlueprintQuery GenericQuery;
        GenericQuery.Sql = Query.Sql;
        GenericQuery.ResultSourceName = Query.ResultSourceName;
        return GenericQuery;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GameState|Columns", meta=(DisplayName="GameState Status"))
    static FBlueprintStringColumn GameStateStatus(const FGameStateQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("game_state") : Query.ResultSourceName;
        Column.ColumnName = TEXT("status");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GameState", meta=(DisplayName="GameState Where"))
    static FGameStateQuery GameStateWhere(FGameStateQuery Query, const FBlueprintPredicate& Predicate)
    {
        if (Query.ResultSourceName != Predicate.ResultSourceName || Predicate.Sql.IsEmpty())
        {
            return Query;
        }
        Query.Sql = AppendPredicate(Query.Sql, Predicate.Sql);
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult", meta=(DisplayName="From GuessResult"))
    static FGuessResultQuery FromGuessResult()
    {
        FGuessResultQuery Query;
        Query.Sql = FString(UTF8_TO_TCHAR(FQueryBuilder().From.GuessResult().into_sql().c_str()));
        Query.ResultSourceName = TEXT("guess_result");
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult", meta=(DisplayName="To Query", BlueprintAutocast))
    static FBlueprintQuery Conv_GuessResultQueryToBlueprintQuery(const FGuessResultQuery& Query)
    {
        FBlueprintQuery GenericQuery;
        GenericQuery.Sql = Query.Sql;
        GenericQuery.ResultSourceName = Query.ResultSourceName;
        return GenericQuery;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult|Columns", meta=(DisplayName="GuessResult PlayerIdentity"))
    static FBlueprintIdentityColumn GuessResultPlayerIdentity(const FGuessResultQuery& Query)
    {
        FBlueprintIdentityColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("guess_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("player_identity");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult|Columns", meta=(DisplayName="GuessResult PlayerName"))
    static FBlueprintStringColumn GuessResultPlayerName(const FGuessResultQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("guess_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("player_name");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult|Columns", meta=(DisplayName="GuessResult Guess"))
    static FBlueprintStringColumn GuessResultGuess(const FGuessResultQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("guess_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("guess");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult|Columns", meta=(DisplayName="GuessResult IsOut"))
    static FBlueprintBoolColumn GuessResultIsOut(const FGuessResultQuery& Query)
    {
        FBlueprintBoolColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("guess_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("is_out");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult|Columns", meta=(DisplayName="GuessResult CreatedAt"))
    static FBlueprintTimestampColumn GuessResultCreatedAt(const FGuessResultQuery& Query)
    {
        FBlueprintTimestampColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("guess_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("created_at");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|GuessResult", meta=(DisplayName="GuessResult Where"))
    static FGuessResultQuery GuessResultWhere(FGuessResultQuery Query, const FBlueprintPredicate& Predicate)
    {
        if (Query.ResultSourceName != Predicate.ResultSourceName || Predicate.Sql.IsEmpty())
        {
            return Query;
        }
        Query.Sql = AppendPredicate(Query.Sql, Predicate.Sql);
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Player", meta=(DisplayName="From Player"))
    static FPlayerQuery FromPlayer()
    {
        FPlayerQuery Query;
        Query.Sql = FString(UTF8_TO_TCHAR(FQueryBuilder().From.Player().into_sql().c_str()));
        Query.ResultSourceName = TEXT("player");
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Player", meta=(DisplayName="To Query", BlueprintAutocast))
    static FBlueprintQuery Conv_PlayerQueryToBlueprintQuery(const FPlayerQuery& Query)
    {
        FBlueprintQuery GenericQuery;
        GenericQuery.Sql = Query.Sql;
        GenericQuery.ResultSourceName = Query.ResultSourceName;
        return GenericQuery;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Player|Columns", meta=(DisplayName="Player Identity"))
    static FBlueprintIdentityColumn PlayerIdentity(const FPlayerQuery& Query)
    {
        FBlueprintIdentityColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("player") : Query.ResultSourceName;
        Column.ColumnName = TEXT("identity");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Player|Columns", meta=(DisplayName="Player Name"))
    static FBlueprintStringColumn PlayerName(const FPlayerQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("player") : Query.ResultSourceName;
        Column.ColumnName = TEXT("name");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Player|Columns", meta=(DisplayName="Player Online"))
    static FBlueprintBoolColumn PlayerOnline(const FPlayerQuery& Query)
    {
        FBlueprintBoolColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("player") : Query.ResultSourceName;
        Column.ColumnName = TEXT("online");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Player", meta=(DisplayName="Player Where"))
    static FPlayerQuery PlayerWhere(FPlayerQuery Query, const FBlueprintPredicate& Predicate)
    {
        if (Query.ResultSourceName != Predicate.ResultSourceName || Predicate.Sql.IsEmpty())
        {
            return Query;
        }
        Query.Sql = AppendPredicate(Query.Sql, Predicate.Sql);
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealGuessLog", meta=(DisplayName="From UnrealGuessLog"))
    static FUnrealGuessLogQuery FromUnrealGuessLog()
    {
        FUnrealGuessLogQuery Query;
        Query.Sql = FString(UTF8_TO_TCHAR(FQueryBuilder().From.UnrealGuessLog().into_sql().c_str()));
        Query.ResultSourceName = TEXT("unreal_guess_log");
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealGuessLog", meta=(DisplayName="To Query", BlueprintAutocast))
    static FBlueprintQuery Conv_UnrealGuessLogQueryToBlueprintQuery(const FUnrealGuessLogQuery& Query)
    {
        FBlueprintQuery GenericQuery;
        GenericQuery.Sql = Query.Sql;
        GenericQuery.ResultSourceName = Query.ResultSourceName;
        return GenericQuery;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealGuessLog|Columns", meta=(DisplayName="UnrealGuessLog SessionId"))
    static FBlueprintStringColumn UnrealGuessLogSessionId(const FUnrealGuessLogQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_guess_log") : Query.ResultSourceName;
        Column.ColumnName = TEXT("session_id");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealGuessLog|Columns", meta=(DisplayName="UnrealGuessLog Guess"))
    static FBlueprintStringColumn UnrealGuessLogGuess(const FUnrealGuessLogQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_guess_log") : Query.ResultSourceName;
        Column.ColumnName = TEXT("guess");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealGuessLog|Columns", meta=(DisplayName="UnrealGuessLog IsOut"))
    static FBlueprintBoolColumn UnrealGuessLogIsOut(const FUnrealGuessLogQuery& Query)
    {
        FBlueprintBoolColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_guess_log") : Query.ResultSourceName;
        Column.ColumnName = TEXT("is_out");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealGuessLog|Columns", meta=(DisplayName="UnrealGuessLog CreatedAt"))
    static FBlueprintTimestampColumn UnrealGuessLogCreatedAt(const FUnrealGuessLogQuery& Query)
    {
        FBlueprintTimestampColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_guess_log") : Query.ResultSourceName;
        Column.ColumnName = TEXT("created_at");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealGuessLog", meta=(DisplayName="UnrealGuessLog Where"))
    static FUnrealGuessLogQuery UnrealGuessLogWhere(FUnrealGuessLogQuery Query, const FBlueprintPredicate& Predicate)
    {
        if (Query.ResultSourceName != Predicate.ResultSourceName || Predicate.Sql.IsEmpty())
        {
            return Query;
        }
        Query.Sql = AppendPredicate(Query.Sql, Predicate.Sql);
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealPlayerStats", meta=(DisplayName="From UnrealPlayerStats"))
    static FUnrealPlayerStatsQuery FromUnrealPlayerStats()
    {
        FUnrealPlayerStatsQuery Query;
        Query.Sql = FString(UTF8_TO_TCHAR(FQueryBuilder().From.UnrealPlayerStats().into_sql().c_str()));
        Query.ResultSourceName = TEXT("unreal_player_stats");
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealPlayerStats", meta=(DisplayName="To Query", BlueprintAutocast))
    static FBlueprintQuery Conv_UnrealPlayerStatsQueryToBlueprintQuery(const FUnrealPlayerStatsQuery& Query)
    {
        FBlueprintQuery GenericQuery;
        GenericQuery.Sql = Query.Sql;
        GenericQuery.ResultSourceName = Query.ResultSourceName;
        return GenericQuery;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealPlayerStats", meta=(DisplayName="UnrealPlayerStats Where"))
    static FUnrealPlayerStatsQuery UnrealPlayerStatsWhere(FUnrealPlayerStatsQuery Query, const FBlueprintPredicate& Predicate)
    {
        if (Query.ResultSourceName != Predicate.ResultSourceName || Predicate.Sql.IsEmpty())
        {
            return Query;
        }
        Query.Sql = AppendPredicate(Query.Sql, Predicate.Sql);
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealRoundResult", meta=(DisplayName="From UnrealRoundResult"))
    static FUnrealRoundResultQuery FromUnrealRoundResult()
    {
        FUnrealRoundResultQuery Query;
        Query.Sql = FString(UTF8_TO_TCHAR(FQueryBuilder().From.UnrealRoundResult().into_sql().c_str()));
        Query.ResultSourceName = TEXT("unreal_round_result");
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealRoundResult", meta=(DisplayName="To Query", BlueprintAutocast))
    static FBlueprintQuery Conv_UnrealRoundResultQueryToBlueprintQuery(const FUnrealRoundResultQuery& Query)
    {
        FBlueprintQuery GenericQuery;
        GenericQuery.Sql = Query.Sql;
        GenericQuery.ResultSourceName = Query.ResultSourceName;
        return GenericQuery;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealRoundResult|Columns", meta=(DisplayName="UnrealRoundResult SessionId"))
    static FBlueprintStringColumn UnrealRoundResultSessionId(const FUnrealRoundResultQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_round_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("session_id");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealRoundResult|Columns", meta=(DisplayName="UnrealRoundResult Answer"))
    static FBlueprintStringColumn UnrealRoundResultAnswer(const FUnrealRoundResultQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_round_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("answer");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealRoundResult|Columns", meta=(DisplayName="UnrealRoundResult Status"))
    static FBlueprintStringColumn UnrealRoundResultStatus(const FUnrealRoundResultQuery& Query)
    {
        FBlueprintStringColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_round_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("status");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealRoundResult|Columns", meta=(DisplayName="UnrealRoundResult EndedAt"))
    static FBlueprintTimestampColumn UnrealRoundResultEndedAt(const FUnrealRoundResultQuery& Query)
    {
        FBlueprintTimestampColumn Column;
        Column.ResultSourceName = Query.ResultSourceName.IsEmpty() ? TEXT("unreal_round_result") : Query.ResultSourceName;
        Column.ColumnName = TEXT("ended_at");
        return Column;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|UnrealRoundResult", meta=(DisplayName="UnrealRoundResult Where"))
    static FUnrealRoundResultQuery UnrealRoundResultWhere(FUnrealRoundResultQuery Query, const FBlueprintPredicate& Predicate)
    {
        if (Query.ResultSourceName != Predicate.ResultSourceName || Predicate.Sql.IsEmpty())
        {
            return Query;
        }
        Query.Sql = AppendPredicate(Query.Sql, Predicate.Sql);
        return Query;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Bool Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate BoolEqual(const FBlueprintBoolColumn& Column, const bool Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="UInt8 Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate UInt8Equal(const FBlueprintUInt8Column& Column, const uint8 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="UInt8 Greater Than", CompactNodeTitle=">", Keywords="> greater"))
    static FBlueprintPredicate UInt8GreaterThan(const FBlueprintUInt8Column& Column, const uint8 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" > %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="UInt8 Greater Equal", CompactNodeTitle=">=", Keywords=">= greater equal"))
    static FBlueprintPredicate UInt8GreaterEqual(const FBlueprintUInt8Column& Column, const uint8 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" >= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="UInt8 Less Than", CompactNodeTitle="<", Keywords="< less"))
    static FBlueprintPredicate UInt8LessThan(const FBlueprintUInt8Column& Column, const uint8 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" < %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="UInt8 Less Equal", CompactNodeTitle="<=", Keywords="<= less equal"))
    static FBlueprintPredicate UInt8LessEqual(const FBlueprintUInt8Column& Column, const uint8 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" <= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int32 Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate Int32Equal(const FBlueprintInt32Column& Column, const int32 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int32 Greater Than", CompactNodeTitle=">", Keywords="> greater"))
    static FBlueprintPredicate Int32GreaterThan(const FBlueprintInt32Column& Column, const int32 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" > %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int32 Greater Equal", CompactNodeTitle=">=", Keywords=">= greater equal"))
    static FBlueprintPredicate Int32GreaterEqual(const FBlueprintInt32Column& Column, const int32 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" >= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int32 Less Than", CompactNodeTitle="<", Keywords="< less"))
    static FBlueprintPredicate Int32LessThan(const FBlueprintInt32Column& Column, const int32 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" < %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int32 Less Equal", CompactNodeTitle="<=", Keywords="<= less equal"))
    static FBlueprintPredicate Int32LessEqual(const FBlueprintInt32Column& Column, const int32 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" <= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int64 Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate Int64Equal(const FBlueprintInt64Column& Column, const int64 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int64 Greater Than", CompactNodeTitle=">", Keywords="> greater"))
    static FBlueprintPredicate Int64GreaterThan(const FBlueprintInt64Column& Column, const int64 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" > %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int64 Greater Equal", CompactNodeTitle=">=", Keywords=">= greater equal"))
    static FBlueprintPredicate Int64GreaterEqual(const FBlueprintInt64Column& Column, const int64 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" >= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int64 Less Than", CompactNodeTitle="<", Keywords="< less"))
    static FBlueprintPredicate Int64LessThan(const FBlueprintInt64Column& Column, const int64 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" < %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Int64 Less Equal", CompactNodeTitle="<=", Keywords="<= less equal"))
    static FBlueprintPredicate Int64LessEqual(const FBlueprintInt64Column& Column, const int64 Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" <= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Float Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate FloatEqual(const FBlueprintFloatColumn& Column, const float Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Float Greater Than", CompactNodeTitle=">", Keywords="> greater"))
    static FBlueprintPredicate FloatGreaterThan(const FBlueprintFloatColumn& Column, const float Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" > %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Float Greater Equal", CompactNodeTitle=">=", Keywords=">= greater equal"))
    static FBlueprintPredicate FloatGreaterEqual(const FBlueprintFloatColumn& Column, const float Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" >= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Float Less Than", CompactNodeTitle="<", Keywords="< less"))
    static FBlueprintPredicate FloatLessThan(const FBlueprintFloatColumn& Column, const float Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" < %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Float Less Equal", CompactNodeTitle="<=", Keywords="<= less equal"))
    static FBlueprintPredicate FloatLessEqual(const FBlueprintFloatColumn& Column, const float Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" <= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Double Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate DoubleEqual(const FBlueprintDoubleColumn& Column, const double Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Double Greater Than", CompactNodeTitle=">", Keywords="> greater"))
    static FBlueprintPredicate DoubleGreaterThan(const FBlueprintDoubleColumn& Column, const double Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" > %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Double Greater Equal", CompactNodeTitle=">=", Keywords=">= greater equal"))
    static FBlueprintPredicate DoubleGreaterEqual(const FBlueprintDoubleColumn& Column, const double Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" >= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Double Less Than", CompactNodeTitle="<", Keywords="< less"))
    static FBlueprintPredicate DoubleLessThan(const FBlueprintDoubleColumn& Column, const double Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" < %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Double Less Equal", CompactNodeTitle="<=", Keywords="<= less equal"))
    static FBlueprintPredicate DoubleLessEqual(const FBlueprintDoubleColumn& Column, const double Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" <= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="String Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate StringEqual(const FBlueprintStringColumn& Column, const FString& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Identity Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate IdentityEqual(const FBlueprintIdentityColumn& Column, const FSpacetimeDBIdentity& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="ConnectionId Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate ConnectionIdEqual(const FBlueprintConnectionIdColumn& Column, const FSpacetimeDBConnectionId& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Timestamp Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate TimestampEqual(const FBlueprintTimestampColumn& Column, const FSpacetimeDBTimestamp& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Timestamp Greater Than", CompactNodeTitle=">", Keywords="> greater"))
    static FBlueprintPredicate TimestampGreaterThan(const FBlueprintTimestampColumn& Column, const FSpacetimeDBTimestamp& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" > %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Timestamp Greater Equal", CompactNodeTitle=">=", Keywords=">= greater equal"))
    static FBlueprintPredicate TimestampGreaterEqual(const FBlueprintTimestampColumn& Column, const FSpacetimeDBTimestamp& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" >= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Timestamp Less Than", CompactNodeTitle="<", Keywords="< less"))
    static FBlueprintPredicate TimestampLessThan(const FBlueprintTimestampColumn& Column, const FSpacetimeDBTimestamp& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" < %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Timestamp Less Equal", CompactNodeTitle="<=", Keywords="<= less equal"))
    static FBlueprintPredicate TimestampLessEqual(const FBlueprintTimestampColumn& Column, const FSpacetimeDBTimestamp& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" <= %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="Uuid Equal", CompactNodeTitle="==", Keywords="== equal"))
    static FBlueprintPredicate UuidEqual(const FBlueprintUuidColumn& Column, const FSpacetimeDBUuid& Value)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = Column.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("\"%s\".\"%s\" = %s"), *Column.ResultSourceName, *Column.ColumnName, UTF8_TO_TCHAR(::SpacetimeDB::query_builder::detail::literal_sql(Value).c_str()));
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="AND", CompactNodeTitle="AND", Keywords="and &&"))
    static FBlueprintPredicate And(const FBlueprintPredicate& A, const FBlueprintPredicate& B)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = A.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("(%s) AND (%s)"), *A.Sql, *B.Sql);
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="OR", CompactNodeTitle="OR", Keywords="or ||"))
    static FBlueprintPredicate Or(const FBlueprintPredicate& A, const FBlueprintPredicate& B)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = A.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("(%s) OR (%s)"), *A.Sql, *B.Sql);
        return Predicate;
    }

    UFUNCTION(BlueprintPure, Category="SpacetimeDB|Queries|Predicates", meta=(DisplayName="NOT", CompactNodeTitle="NOT", Keywords="not !"))
    static FBlueprintPredicate Not(const FBlueprintPredicate& A)
    {
        FBlueprintPredicate Predicate;
        Predicate.ResultSourceName = A.ResultSourceName;
        Predicate.Sql = FString::Printf(TEXT("NOT (%s)"), *A.Sql);
        return Predicate;
    }

private:
    static FString AppendPredicate(const FString& Sql, const FString& Predicate)
    {
        if (Sql.Contains(TEXT(" WHERE ")))
        {
            return Sql + TEXT(" AND (") + Predicate + TEXT(")");
        }
        return Sql + TEXT(" WHERE (") + Predicate + TEXT(")");
    }
};

// SubscriptionBuilder class
UCLASS(BlueprintType)
class CH_4_API USubscriptionBuilder : public USubscriptionBuilderBase
{
    GENERATED_BODY()

public:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionBuilder* OnApplied(FOnSubscriptionApplied Callback);

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionBuilder* OnError(FOnSubscriptionError Callback);

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionHandle* Subscribe();

    USubscriptionHandle* Subscribe(const TArray<FString>& SQL);

    template<typename TFn>
    USubscriptionBuilder* AddQuery(TFn&& Build)
    {
        FQueryBuilder Q;
        auto Query = std::forward<TFn>(Build)(Q);
        static_assert(::SpacetimeDB::query_builder::QueryBuilderReturn<decltype(Query)>,
            "Typed subscription queries must return a query_builder table/query expression.");
        PendingSqlQueries.Add(FString(UTF8_TO_TCHAR(Query.into_sql().c_str())));
        return this;
    }

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB", meta=(DisplayName="AddQuery", ScriptName="AddQuery"))
    USubscriptionBuilder* AddBlueprintQuery(const FBlueprintQuery& Query);

    USubscriptionBuilder* AddGameStateQuery(const FGameStateQuery& Query);

    USubscriptionBuilder* AddGuessResultQuery(const FGuessResultQuery& Query);

    USubscriptionBuilder* AddPlayerQuery(const FPlayerQuery& Query);

    USubscriptionBuilder* AddUnrealGuessLogQuery(const FUnrealGuessLogQuery& Query);

    USubscriptionBuilder* AddUnrealPlayerStatsQuery(const FUnrealPlayerStatsQuery& Query);

    USubscriptionBuilder* AddUnrealRoundResultQuery(const FUnrealRoundResultQuery& Query);

    /** Convenience for subscribing to all rows from all public sources, including views */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionHandle* SubscribeToAllTables();


    friend class UDbConnection;
    friend class UDbConnectionBase;

protected:
    UPROPERTY()
    class UDbConnection* Conn;

    UPROPERTY()
    TArray<FString> PendingSqlQueries;

    // Delegates stored so Subscribe() can bind forwarding callbacks
    FOnSubscriptionApplied OnAppliedDelegateInternal;
    FOnSubscriptionError OnErrorDelegateInternal;
};

// SubscriptionHandle class
UCLASS(BlueprintType)
class CH_4_API USubscriptionHandle : public USubscriptionHandleBase
{
    GENERATED_BODY()

public:

    USubscriptionHandle() {};

    explicit USubscriptionHandle(UDbConnection* InConn);

    friend class USubscriptionBuilder;

private:
    UPROPERTY()
    class UDbConnection* Conn;

    // Delegates that expose subscription events with connection aware contexts
    FOnSubscriptionApplied OnAppliedDelegate;
    FOnSubscriptionError OnErrorDelegate;

    UFUNCTION()
    void ForwardOnApplied(const FSubscriptionEventContextBase& BaseCtx);

    UFUNCTION()
    void ForwardOnError(const FErrorContextBase& BaseCtx);
};

/*
    @Note: Child class of UDbConnectionBuilderBase.
*/
UCLASS(BlueprintType)
class CH_4_API UDbConnectionBuilder : public UDbConnectionBuilderBase
{
    GENERATED_BODY()
public:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithUri(const FString& InUri);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithDatabaseName(const FString& InName);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithToken(const FString& InToken);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithCompression(const ESpacetimeDBCompression& InCompression);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnConnect(FOnConnectDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnConnectError(FOnConnectErrorDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnDisconnect(FOnDisconnectDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnection* Build();

private:

    // Stored delegates which will be forwarded when the connection events occur.
    FOnConnectDelegate OnConnectDelegateInternal;
    FOnDisconnectDelegate OnDisconnectDelegateInternal;
};

// Main DbConnection class
UCLASS(BlueprintType)
class CH_4_API UDbConnection : public UDbConnectionBase
{
    GENERATED_BODY()

public:
    explicit UDbConnection(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get());


    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteTables* Db;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteReducers* Reducers;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteProcedures* Procedures;

    // Delegates that allow users to bind with the concrete connection type.
    FOnConnectDelegate OnConnectDelegate;
    FOnDisconnectDelegate OnDisconnectDelegate;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionBuilder* SubscriptionBuilder();

    /** Static entry point for constructing a connection. */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB", DisplayName = "SpacetimeDB CH_4 Builder")
    static UDbConnectionBuilder* Builder();

    // Error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FOnUnhandledReducerError OnUnhandledReducerError;

    // Error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnUnhandledProcedureError, const FProcedureEventContext&, Context, const FString&, Error);
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FOnUnhandledProcedureError OnUnhandledProcedureError;


protected:

    // Hook up error handling to reducers and procedures
    virtual void PostInitProperties() override;

    UFUNCTION()
    void ForwardOnConnect(UDbConnectionBase* BaseConnection, FSpacetimeDBIdentity InIdentity, const FString& InToken);
    UFUNCTION()
    void ForwardOnDisconnect(UDbConnectionBase* BaseConnection, const FString& Error);

    UFUNCTION()
    void OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error);

    UFUNCTION()
    void OnUnhandledProcedureErrorHandler(const FProcedureEventContext& Context, const FString& Error);

    // Override the DbConnectionBase methods to handle updates and events
    virtual void DbUpdate(const FDatabaseUpdateType& Update, const FSpacetimeDBEvent& Event) override;
    
    // Override the reducer event handler to dispatch events to the appropriate reducers
    virtual void ReducerEvent(const FReducerEvent& Event) override;
    
    // Override the reducer event failed handler
    virtual void ReducerEventFailed(const FReducerEvent& Event, const FString ErrorMessage) override;
    // Override the procedure event failed handler
    virtual void ProcedureEventFailed(const FProcedureEvent& Event, const FString ErrorMessage) override;

    friend class USubscriptionBuilder;
    friend class UDbConnectionBuilder;
    friend class URemoteReducers;

    // Internal reducer correlation helpers (request_id -> typed reducer)
    void RegisterPendingTypedReducer(uint32 RequestId, FReducer Reducer);
    bool TryGetPendingTypedReducer(uint32 RequestId, FReducer& OutReducer) const;
    bool TryTakePendingTypedReducer(uint32 RequestId, FReducer& OutReducer);

private:
    TMap<uint32, FReducer> PendingTypedReducers;
};

