// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/SpacetimeDBClient.g.h"
#include "DBCache/WithBsatn.h"
#include "BSATN/UEBSATNHelpers.h"
#include "ModuleBindings/Tables/GameStateTable.g.h"
#include "ModuleBindings/Tables/GuessResultTable.g.h"
#include "ModuleBindings/Tables/PlayerTable.g.h"
#include "ModuleBindings/Tables/UnrealGuessLogTable.g.h"
#include "ModuleBindings/Tables/UnrealPlayerStatsTable.g.h"
#include "ModuleBindings/Tables/UnrealRoundResultTable.g.h"

UDbConnection::UDbConnection(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer)
{
	Db = ObjectInitializer.CreateDefaultSubobject<URemoteTables>(this, TEXT("RemoteTables"));
	Db->Initialize();
	
	Reducers = ObjectInitializer.CreateDefaultSubobject<URemoteReducers>(this, TEXT("RemoteReducers"));
	Reducers->Conn = this;

	Procedures = ObjectInitializer.CreateDefaultSubobject<URemoteProcedures>(this, TEXT("RemoteProcedures"));
	Procedures->Conn = this;

	RegisterTable<FGameStateType, UGameStateTable, FEventContext>(TEXT("game_state"), Db->GameState);
	RegisterTable<FGuessResultType, UGuessResultTable, FEventContext>(TEXT("guess_result"), Db->GuessResult);
	RegisterTable<FPlayerType, UPlayerTable, FEventContext>(TEXT("player"), Db->Player);
	RegisterTable<FUnrealGuessLogType, UUnrealGuessLogTable, FEventContext>(TEXT("unreal_guess_log"), Db->UnrealGuessLog);
	RegisterTable<FUnrealPlayerStatsType, UUnrealPlayerStatsTable, FEventContext>(TEXT("unreal_player_stats"), Db->UnrealPlayerStats);
	RegisterTable<FUnrealRoundResultType, UUnrealRoundResultTable, FEventContext>(TEXT("unreal_round_result"), Db->UnrealRoundResult);
}

FContextBase::FContextBase(UDbConnection* InConn)
{
	Db = InConn->Db;
	Reducers = InConn->Reducers;
	Procedures = InConn->Procedures;
	Conn = InConn;
}
bool FContextBase::IsActive() const
{
	return Conn->IsActive();
}
void FContextBase::Disconnect()
{
	Conn->Disconnect();
}
USubscriptionBuilder* FContextBase::SubscriptionBuilder()
{
	return Conn->SubscriptionBuilder();
}
bool FContextBase::TryGetIdentity(FSpacetimeDBIdentity& OutIdentity) const
{
	return Conn->TryGetIdentity(OutIdentity);
}
FSpacetimeDBConnectionId FContextBase::GetConnectionId() const
{
	return Conn->GetConnectionId();
}

void URemoteTables::Initialize()
{

	/** Creating tables */
	GameState = NewObject<UGameStateTable>(this);
	GuessResult = NewObject<UGuessResultTable>(this);
	Player = NewObject<UPlayerTable>(this);
	UnrealGuessLog = NewObject<UUnrealGuessLogTable>(this);
	UnrealPlayerStats = NewObject<UUnrealPlayerStatsTable>(this);
	UnrealRoundResult = NewObject<UUnrealRoundResultTable>(this);
	/**/

	/** Initialization */
	GameState->PostInitialize();
	GuessResult->PostInitialize();
	Player->PostInitialize();
	UnrealGuessLog->PostInitialize();
	UnrealPlayerStats->PostInitialize();
	UnrealRoundResult->PostInitialize();
	/**/
}

void URemoteReducers::RecordUnrealGuess(const FString& SessionId, const uint32 Round, const uint32 PlayerNumber, const FString& Guess, const uint32 Strikes, const uint32 Balls, const uint32 AttemptNumber)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FRecordUnrealGuessArgs ReducerArgs(SessionId, Round, PlayerNumber, Guess, Strikes, Balls, AttemptNumber);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("record_unreal_guess"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::RecordUnrealGuess(ReducerArgs)); }
}

bool URemoteReducers::InvokeRecordUnrealGuess(const FReducerEventContext& Context, const URecordUnrealGuessReducer* Args)
{
    if (!OnRecordUnrealGuess.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for RecordUnrealGuess"));
        }
        return false;
    }

    OnRecordUnrealGuess.Broadcast(Context, Args->SessionId, Args->Round, Args->PlayerNumber, Args->Guess, Args->Strikes, Args->Balls, Args->AttemptNumber);
    return true;
}

bool URemoteReducers::InvokeRecordUnrealGuessWithArgs(const FReducerEventContext& Context, const FRecordUnrealGuessArgs& Args)
{
    if (!OnRecordUnrealGuess.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for RecordUnrealGuess"));
        }
        return false;
    }

    OnRecordUnrealGuess.Broadcast(Context, Args.SessionId, Args.Round, Args.PlayerNumber, Args.Guess, Args.Strikes, Args.Balls, Args.AttemptNumber);
    return true;
}

void URemoteReducers::RecordUnrealRoundResult(const FString& SessionId, const uint32 Round, const FString& Answer, const FString& Status, const uint32 WinnerPlayerNumber)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FRecordUnrealRoundResultArgs ReducerArgs(SessionId, Round, Answer, Status, WinnerPlayerNumber);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("record_unreal_round_result"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::RecordUnrealRoundResult(ReducerArgs)); }
}

bool URemoteReducers::InvokeRecordUnrealRoundResult(const FReducerEventContext& Context, const URecordUnrealRoundResultReducer* Args)
{
    if (!OnRecordUnrealRoundResult.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for RecordUnrealRoundResult"));
        }
        return false;
    }

    OnRecordUnrealRoundResult.Broadcast(Context, Args->SessionId, Args->Round, Args->Answer, Args->Status, Args->WinnerPlayerNumber);
    return true;
}

bool URemoteReducers::InvokeRecordUnrealRoundResultWithArgs(const FReducerEventContext& Context, const FRecordUnrealRoundResultArgs& Args)
{
    if (!OnRecordUnrealRoundResult.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for RecordUnrealRoundResult"));
        }
        return false;
    }

    OnRecordUnrealRoundResult.Broadcast(Context, Args.SessionId, Args.Round, Args.Answer, Args.Status, Args.WinnerPlayerNumber);
    return true;
}

void URemoteReducers::SetName(const FString& Name)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FSetNameArgs ReducerArgs(Name);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("set_name"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::SetName(ReducerArgs)); }
}

bool URemoteReducers::InvokeSetName(const FReducerEventContext& Context, const USetNameReducer* Args)
{
    if (!OnSetName.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SetName"));
        }
        return false;
    }

    OnSetName.Broadcast(Context, Args->Name);
    return true;
}

bool URemoteReducers::InvokeSetNameWithArgs(const FReducerEventContext& Context, const FSetNameArgs& Args)
{
    if (!OnSetName.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SetName"));
        }
        return false;
    }

    OnSetName.Broadcast(Context, Args.Name);
    return true;
}

void URemoteReducers::StartNewRound()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FStartNewRoundArgs ReducerArgs;
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("start_new_round"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::StartNewRound(ReducerArgs)); }
}

bool URemoteReducers::InvokeStartNewRound(const FReducerEventContext& Context, const UStartNewRoundReducer* Args)
{
    if (!OnStartNewRound.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for StartNewRound"));
        }
        return false;
    }

    OnStartNewRound.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeStartNewRoundWithArgs(const FReducerEventContext& Context, const FStartNewRoundArgs& Args)
{
    if (!OnStartNewRound.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for StartNewRound"));
        }
        return false;
    }

    OnStartNewRound.Broadcast(Context);
    return true;
}

void URemoteReducers::SubmitGuess(const FString& Guess)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FSubmitGuessArgs ReducerArgs(Guess);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("submit_guess"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::SubmitGuess(ReducerArgs)); }
}

bool URemoteReducers::InvokeSubmitGuess(const FReducerEventContext& Context, const USubmitGuessReducer* Args)
{
    if (!OnSubmitGuess.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SubmitGuess"));
        }
        return false;
    }

    OnSubmitGuess.Broadcast(Context, Args->Guess);
    return true;
}

bool URemoteReducers::InvokeSubmitGuessWithArgs(const FReducerEventContext& Context, const FSubmitGuessArgs& Args)
{
    if (!OnSubmitGuess.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SubmitGuess"));
        }
        return false;
    }

    OnSubmitGuess.Broadcast(Context, Args.Guess);
    return true;
}

void UDbConnection::PostInitProperties()
{
    Super::PostInitProperties();
    
    // Connect OnUnhandledReducerError to Reducers.InternalOnUnhandledReducerError
    if (Reducers)
    {
        Reducers->InternalOnUnhandledReducerError.AddDynamic(this, &UDbConnection::OnUnhandledReducerErrorHandler);
    }

    // Connect OnUnhandledProcedureError to Procedures.InternalOnUnhandledProcedureError
    if (Procedures)
    {
        Procedures->InternalOnUnhandledProcedureError.AddDynamic(this, &UDbConnection::OnUnhandledProcedureErrorHandler);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error)
{
    if (OnUnhandledReducerError.IsBound())
    {
        OnUnhandledReducerError.Broadcast(Context, Error);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledProcedureErrorHandler(const FProcedureEventContext& Context, const FString& Error)
{
    if (OnUnhandledProcedureError.IsBound())
    {
        OnUnhandledProcedureError.Broadcast(Context, Error);
    }
}

void UDbConnection::RegisterPendingTypedReducer(uint32 RequestId, FReducer Reducer)
{
    Reducer.RequestId = RequestId;
    PendingTypedReducers.Add(RequestId, MoveTemp(Reducer));
}

bool UDbConnection::TryGetPendingTypedReducer(uint32 RequestId, FReducer& OutReducer) const
{
    if (const FReducer* Found = PendingTypedReducers.Find(RequestId))
    {
        OutReducer = *Found;
        return true;
    }
    return false;
}

bool UDbConnection::TryTakePendingTypedReducer(uint32 RequestId, FReducer& OutReducer)
{
    if (FReducer* Found = PendingTypedReducers.Find(RequestId))
    {
        OutReducer = *Found;
        PendingTypedReducers.Remove(RequestId);
        return true;
    }
    return false;
}

void UDbConnection::ReducerEvent(const FReducerEvent& Event)
{
    if (!Reducers) { return; }

    FReducer DecodedReducer;
    if (!TryTakePendingTypedReducer(Event.RequestId, DecodedReducer))
    {
        const FString ErrorMessage = FString::Printf(TEXT("Reducer result for unknown request_id %u"), Event.RequestId);
        HandleProtocolViolation(ErrorMessage);
        return;
    }

    FCh4ReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;
    ReducerEvent.Reducer            = DecodedReducer;

    FReducerEventContext Context(this, ReducerEvent);

    // Dispatch by typed reducer metadata
    const FString& ReducerName = ReducerEvent.Reducer.ReducerName;

    if (ReducerName == TEXT("record_unreal_guess"))
    {
        FRecordUnrealGuessArgs Args = ReducerEvent.Reducer.GetAsRecordUnrealGuess();
        Reducers->InvokeRecordUnrealGuessWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("record_unreal_round_result"))
    {
        FRecordUnrealRoundResultArgs Args = ReducerEvent.Reducer.GetAsRecordUnrealRoundResult();
        Reducers->InvokeRecordUnrealRoundResultWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("set_name"))
    {
        FSetNameArgs Args = ReducerEvent.Reducer.GetAsSetName();
        Reducers->InvokeSetNameWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("start_new_round"))
    {
        FStartNewRoundArgs Args = ReducerEvent.Reducer.GetAsStartNewRound();
        Reducers->InvokeStartNewRoundWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("submit_guess"))
    {
        FSubmitGuessArgs Args = ReducerEvent.Reducer.GetAsSubmitGuess();
        Reducers->InvokeSubmitGuessWithArgs(Context, Args);
        return;
    }

    UE_LOG(LogTemp, Warning, TEXT("Unknown reducer: %s"), *ReducerName);
}

void UDbConnection::ReducerEventFailed(const FReducerEvent& Event, const FString ErrorMessage)
{
    if (!Reducers) { return; }

    FCh4ReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;

    FReducerEventContext Context(this, ReducerEvent);

    if (Reducers->InternalOnUnhandledReducerError.IsBound())
    {
        Reducers->InternalOnUnhandledReducerError.Broadcast(Context, ErrorMessage);
    }
}

void UDbConnection::ProcedureEventFailed(const FProcedureEvent& Event, const FString ErrorMessage)
{
    if (!Procedures) { return; }

    FCh4ProcedureEvent ProcedureEvent;
    ProcedureEvent.Status             = FSpacetimeDBProcedureStatus::FromStatus(Event.Status);
    ProcedureEvent.Timestamp          = Event.Timestamp;

    FProcedureEventContext Context(this, ProcedureEvent);

    if (Procedures->InternalOnUnhandledProcedureError.IsBound())
    {
        Procedures->InternalOnUnhandledProcedureError.Broadcast(Context, ErrorMessage);
    }
}

UDbConnectionBuilder* UDbConnection::Builder()
{
	return NewObject<UDbConnectionBuilder>();
}
// Added for creating subscriptions
USubscriptionBuilder* UDbConnection::SubscriptionBuilder()
{
	USubscriptionBuilder* Builder = NewObject<USubscriptionBuilder>(this);
	Builder->Conn = this;
	return Builder;
}
USubscriptionBuilder* USubscriptionBuilder::OnApplied(FOnSubscriptionApplied Callback)
{
	OnAppliedDelegateInternal = Callback;
	return this;
}
USubscriptionBuilder* USubscriptionBuilder::OnError(FOnSubscriptionError Callback)
{
	OnErrorDelegateInternal = Callback;
	return this;
}
USubscriptionHandle* USubscriptionBuilder::Subscribe()
{
	const TArray<FString> SqlQueries = PendingSqlQueries;
	PendingSqlQueries.Empty();
	return Subscribe(SqlQueries);
}
USubscriptionHandle* USubscriptionBuilder::Subscribe(const TArray<FString>& SQL)
{
	USubscriptionHandle* Handle = NewObject<USubscriptionHandle>();

	// Store user callbacks on the handle
	Handle->Conn = Conn;
	Handle->OnAppliedDelegate = OnAppliedDelegateInternal;
	Handle->OnErrorDelegate = OnErrorDelegateInternal;

	// Bind forwarding functions that will convert base contexts
	FSubscriptionEventDelegate BaseApplied;
	BaseApplied.BindUFunction(Handle, TEXT("ForwardOnApplied"));
	OnAppliedBase(BaseApplied);

	FSubscriptionErrorDelegate BaseError;
	BaseError.BindUFunction(Handle, TEXT("ForwardOnError"));
	OnErrorBase(BaseError);

	SubscribeBase(SQL, Handle);
	if (Conn)
	{
		Conn->StartSubscription(Handle);
	}
	return Handle;
}
USubscriptionHandle* USubscriptionBuilder::SubscribeToAllTables()
{
	return Subscribe(FQueryBuilder::AllTablesSqlQueries());
}

USubscriptionBuilder* USubscriptionBuilder::AddBlueprintQuery(const FBlueprintQuery& Query)
{
	PendingSqlQueries.Add(Query.Sql);
	return this;
}

USubscriptionBuilder* USubscriptionBuilder::AddGameStateQuery(const FGameStateQuery& Query)
{
	FBlueprintQuery GenericQuery;
	GenericQuery.Sql = Query.Sql;
	GenericQuery.ResultSourceName = Query.ResultSourceName;
	return AddBlueprintQuery(GenericQuery);
}

USubscriptionBuilder* USubscriptionBuilder::AddGuessResultQuery(const FGuessResultQuery& Query)
{
	FBlueprintQuery GenericQuery;
	GenericQuery.Sql = Query.Sql;
	GenericQuery.ResultSourceName = Query.ResultSourceName;
	return AddBlueprintQuery(GenericQuery);
}

USubscriptionBuilder* USubscriptionBuilder::AddPlayerQuery(const FPlayerQuery& Query)
{
	FBlueprintQuery GenericQuery;
	GenericQuery.Sql = Query.Sql;
	GenericQuery.ResultSourceName = Query.ResultSourceName;
	return AddBlueprintQuery(GenericQuery);
}

USubscriptionBuilder* USubscriptionBuilder::AddUnrealGuessLogQuery(const FUnrealGuessLogQuery& Query)
{
	FBlueprintQuery GenericQuery;
	GenericQuery.Sql = Query.Sql;
	GenericQuery.ResultSourceName = Query.ResultSourceName;
	return AddBlueprintQuery(GenericQuery);
}

USubscriptionBuilder* USubscriptionBuilder::AddUnrealPlayerStatsQuery(const FUnrealPlayerStatsQuery& Query)
{
	FBlueprintQuery GenericQuery;
	GenericQuery.Sql = Query.Sql;
	GenericQuery.ResultSourceName = Query.ResultSourceName;
	return AddBlueprintQuery(GenericQuery);
}

USubscriptionBuilder* USubscriptionBuilder::AddUnrealRoundResultQuery(const FUnrealRoundResultQuery& Query)
{
	FBlueprintQuery GenericQuery;
	GenericQuery.Sql = Query.Sql;
	GenericQuery.ResultSourceName = Query.ResultSourceName;
	return AddBlueprintQuery(GenericQuery);
}

USubscriptionHandle::USubscriptionHandle(UDbConnection* InConn)
{
	Conn = InConn;
}

void USubscriptionHandle::ForwardOnApplied(const FSubscriptionEventContextBase& BaseCtx)
{
	if (OnAppliedDelegate.IsBound())
	{
		FSubscriptionEventContext Ctx(Conn);
		OnAppliedDelegate.Execute(Ctx);
	}
}

void USubscriptionHandle::ForwardOnError(const FErrorContextBase& BaseCtx)
{
	if (OnErrorDelegate.IsBound())
	{
		FErrorContext Ctx(Conn, BaseCtx.Error);
		OnErrorDelegate.Execute(Ctx);
	}
}


// Cast from parent to child class
UDbConnectionBuilder* UDbConnectionBuilder::WithUri(const FString& InUri)
{
	return Cast<UDbConnectionBuilder>(WithUriBase(InUri));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithDatabaseName(const FString& InName)
{
	return Cast<UDbConnectionBuilder>(WithDatabaseNameBase(InName));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithToken(const FString& InToken)
{
	return Cast<UDbConnectionBuilder>(WithTokenBase(InToken));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithCompression(const ESpacetimeDBCompression& InCompression)
{
	return Cast<UDbConnectionBuilder>(WithCompressionBase(InCompression));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnect(FOnConnectDelegate Callback)
{
	OnConnectDelegateInternal = Callback;
	return this;
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnectError(FOnConnectErrorDelegate Callback)
{
	return Cast<UDbConnectionBuilder>(OnConnectErrorBase(Callback));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnDisconnect(FOnDisconnectDelegate Callback)
{
	OnDisconnectDelegateInternal = Callback;
	return this;
}
UDbConnection* UDbConnectionBuilder::Build()
{
	UDbConnection* Connection = NewObject<UDbConnection>();

	// Store delegates on the connection for later use
	Connection->OnConnectDelegate = OnConnectDelegateInternal;
	Connection->OnDisconnectDelegate = OnDisconnectDelegateInternal;

	// Wrap delegates so the base builder can bind them
	FOnConnectBaseDelegate BaseConnect;
	BaseConnect.BindUFunction(Connection, TEXT("ForwardOnConnect"));
	Connection->SetOnConnectDelegate(BaseConnect);
	OnConnectBase(BaseConnect);

	FOnDisconnectBaseDelegate BaseDisconnect;
	BaseDisconnect.BindUFunction(Connection, TEXT("ForwardOnDisconnect"));
	Connection->SetOnDisconnectDelegate(BaseDisconnect);
	OnDisconnectBase(BaseDisconnect);

	return Cast<UDbConnection>(BuildConnection(Connection));
}
void UDbConnection::ForwardOnConnect(UDbConnectionBase* BaseConnection, FSpacetimeDBIdentity InIdentity, const FString& InToken)
{
	if (OnConnectDelegate.IsBound())
	{
		OnConnectDelegate.Execute(this, InIdentity, InToken);
	}
}
void UDbConnection::ForwardOnDisconnect(UDbConnectionBase* BaseConnection, const FString& Error)
{
	PendingTypedReducers.Empty();
	if (OnDisconnectDelegate.IsBound())
	{
		OnDisconnectDelegate.Execute(this, Error);
	}
}


void UDbConnection::DbUpdate(const FDatabaseUpdateType& Update, const FSpacetimeDBEvent& Event)
{
    FCh4Event BaseEvent;
    BaseEvent.Tag = Event.Tag;

    switch (Event.Tag)
    {
    case ESpacetimeDBEventTag::Reducer:
    {
        FReducerEvent ReducerEvent = Event.GetAsReducer();
        FReducer Reducer;
        if (!TryGetPendingTypedReducer(ReducerEvent.RequestId, Reducer))
        {
            const FString ErrorMessage = FString::Printf(TEXT("Reducer result for unknown request_id %u"), ReducerEvent.RequestId);
            HandleProtocolViolation(ErrorMessage);
            return;
        }
        BaseEvent = FCh4Event::Reducer(Reducer);
        break;
    }

    case ESpacetimeDBEventTag::SubscribeApplied:
        BaseEvent = FCh4Event::SubscribeApplied(Event.GetAsSubscribeApplied());
        break;

    case ESpacetimeDBEventTag::UnsubscribeApplied:
        BaseEvent = FCh4Event::UnsubscribeApplied(Event.GetAsUnsubscribeApplied());
        break;

    case ESpacetimeDBEventTag::Disconnected:
        BaseEvent = FCh4Event::Disconnected(Event.GetAsDisconnected());
        break;

    case ESpacetimeDBEventTag::Transaction:
        BaseEvent = FCh4Event::Transaction(Event.GetAsTransaction());
        break;

    case ESpacetimeDBEventTag::SubscribeError:
        BaseEvent = FCh4Event::SubscribeError(Event.GetAsSubscribeError());
        break;

    case ESpacetimeDBEventTag::UnknownTransaction:
        BaseEvent = FCh4Event::UnknownTransaction(Event.GetAsUnknownTransaction());
        break;

    default:
        break;
    }

    FEventContext Context(this, BaseEvent);
    // Populate typed reducer args for convenience in table handlers

    ApplyRegisteredTableUpdates(Update, &Context);
}

