// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "RecordUnrealGuess.g.generated.h"

// Reducer arguments struct for RecordUnrealGuess
USTRUCT(BlueprintType)
struct CH_4_API FRecordUnrealGuessArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString SessionId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 PlayerNumber = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString Guess;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Strikes = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Balls = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 AttemptNumber = 0;

    FRecordUnrealGuessArgs() = default;

    FRecordUnrealGuessArgs(const FString& InSessionId, const uint32& InRound, const uint32& InPlayerNumber, const FString& InGuess, const uint32& InStrikes, const uint32& InBalls, const uint32& InAttemptNumber)
        : SessionId(InSessionId), Round(InRound), PlayerNumber(InPlayerNumber), Guess(InGuess), Strikes(InStrikes), Balls(InBalls), AttemptNumber(InAttemptNumber)
    {}


    FORCEINLINE bool operator==(const FRecordUnrealGuessArgs& Other) const
    {
        return SessionId == Other.SessionId && Round == Other.Round && PlayerNumber == Other.PlayerNumber && Guess == Other.Guess && Strikes == Other.Strikes && Balls == Other.Balls && AttemptNumber == Other.AttemptNumber;
    }
    FORCEINLINE bool operator!=(const FRecordUnrealGuessArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FRecordUnrealGuessArgs, SessionId, Round, PlayerNumber, Guess, Strikes, Balls, AttemptNumber);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CH_4_API URecordUnrealGuessReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString SessionId;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 PlayerNumber = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Guess;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Strikes = 0;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Balls = 0;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 AttemptNumber = 0;

};


