// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "RecordUnrealRoundResult.g.generated.h"

// Reducer arguments struct for RecordUnrealRoundResult
USTRUCT(BlueprintType)
struct CH_4_API FRecordUnrealRoundResultArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString SessionId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString Answer;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString Status;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 WinnerPlayerNumber = 0;

    FRecordUnrealRoundResultArgs() = default;

    FRecordUnrealRoundResultArgs(const FString& InSessionId, const uint32& InRound, const FString& InAnswer, const FString& InStatus, const uint32& InWinnerPlayerNumber)
        : SessionId(InSessionId), Round(InRound), Answer(InAnswer), Status(InStatus), WinnerPlayerNumber(InWinnerPlayerNumber)
    {}


    FORCEINLINE bool operator==(const FRecordUnrealRoundResultArgs& Other) const
    {
        return SessionId == Other.SessionId && Round == Other.Round && Answer == Other.Answer && Status == Other.Status && WinnerPlayerNumber == Other.WinnerPlayerNumber;
    }
    FORCEINLINE bool operator!=(const FRecordUnrealRoundResultArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FRecordUnrealRoundResultArgs, SessionId, Round, Answer, Status, WinnerPlayerNumber);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CH_4_API URecordUnrealRoundResultReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString SessionId;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Answer;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Status;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 WinnerPlayerNumber = 0;

};


