// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "StartNewRound.g.generated.h"

// Reducer arguments struct for StartNewRound
USTRUCT(BlueprintType)
struct CH_4_API FStartNewRoundArgs
{
    GENERATED_BODY()

    FStartNewRoundArgs() = default;


    FORCEINLINE bool operator==(const FStartNewRoundArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FStartNewRoundArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FStartNewRoundArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CH_4_API UStartNewRoundReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


