// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "SubmitGuess.g.generated.h"

// Reducer arguments struct for SubmitGuess
USTRUCT(BlueprintType)
struct CH_4_API FSubmitGuessArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString Guess;

    FSubmitGuessArgs() = default;

    FSubmitGuessArgs(const FString& InGuess)
        : Guess(InGuess)
    {}


    FORCEINLINE bool operator==(const FSubmitGuessArgs& Other) const
    {
        return Guess == Other.Guess;
    }
    FORCEINLINE bool operator!=(const FSubmitGuessArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FSubmitGuessArgs, Guess);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CH_4_API USubmitGuessReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Guess;

};


