// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "GameSecretType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FGameSecretType
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Answer;

    FORCEINLINE bool operator==(const FGameSecretType& Other) const
    {
        return Id == Other.Id && Answer == Other.Answer;
    }

    FORCEINLINE bool operator!=(const FGameSecretType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FGameSecretType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param GameSecretType The FGameSecretType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FGameSecretType& GameSecretType)
{
    uint32 Hash = GetTypeHash(GameSecretType.Id);
    Hash = HashCombine(Hash, GetTypeHash(GameSecretType.Answer));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FGameSecretType);

    UE_SPACETIMEDB_STRUCT(FGameSecretType, Id, Answer);
}
