// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Optionals/Ch4OptionalString.g.h"
#include "GameStateType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FGameStateType
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Id = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Status;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FCh4OptionalString WinnerName;

    FORCEINLINE bool operator==(const FGameStateType& Other) const
    {
        return Id == Other.Id && Round == Other.Round && Status == Other.Status && WinnerName == Other.WinnerName;
    }

    FORCEINLINE bool operator!=(const FGameStateType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FGameStateType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param GameStateType The FGameStateType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FGameStateType& GameStateType)
{
    uint32 Hash = GetTypeHash(GameStateType.Id);
    Hash = HashCombine(Hash, GetTypeHash(GameStateType.Round));
    Hash = HashCombine(Hash, GetTypeHash(GameStateType.Status));
    Hash = HashCombine(Hash, GetTypeHash(GameStateType.WinnerName));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FGameStateType);

    UE_SPACETIMEDB_STRUCT(FGameStateType, Id, Round, Status, WinnerName);
}
