// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "GuessResultType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FGuessResultType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity PlayerIdentity;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString PlayerName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Guess;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Strikes = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Balls = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool IsOut = false;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 AttemptsLeft = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp CreatedAt;

    FORCEINLINE bool operator==(const FGuessResultType& Other) const
    {
        return Id == Other.Id && Round == Other.Round && PlayerIdentity == Other.PlayerIdentity && PlayerName == Other.PlayerName && Guess == Other.Guess && Strikes == Other.Strikes && Balls == Other.Balls && IsOut == Other.IsOut && AttemptsLeft == Other.AttemptsLeft && CreatedAt == Other.CreatedAt;
    }

    FORCEINLINE bool operator!=(const FGuessResultType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FGuessResultType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param GuessResultType The FGuessResultType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FGuessResultType& GuessResultType)
{
    uint32 Hash = GetTypeHash(GuessResultType.Id);
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.Round));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.PlayerIdentity));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.PlayerName));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.Guess));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.Strikes));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.Balls));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.IsOut));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.AttemptsLeft));
    Hash = HashCombine(Hash, GetTypeHash(GuessResultType.CreatedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FGuessResultType);

    UE_SPACETIMEDB_STRUCT(FGuessResultType, Id, Round, PlayerIdentity, PlayerName, Guess, Strikes, Balls, IsOut, AttemptsLeft, CreatedAt);
}
