// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "InitType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FInitType
{
    GENERATED_BODY()

    FORCEINLINE bool operator==(const FInitType& Other) const
    {
        return true;
    }

    FORCEINLINE bool operator!=(const FInitType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FInitType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param InitType The FInitType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FInitType& InitType)
{
    return 0; // Empty struct
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FInitType);

    UE_SPACETIMEDB_STRUCT_EMPTY(FInitType);
}
