// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "OnConnectType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FOnConnectType
{
    GENERATED_BODY()

    FORCEINLINE bool operator==(const FOnConnectType& Other) const
    {
        return true;
    }

    FORCEINLINE bool operator!=(const FOnConnectType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FOnConnectType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param OnConnectType The FOnConnectType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FOnConnectType& OnConnectType)
{
    return 0; // Empty struct
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FOnConnectType);

    UE_SPACETIMEDB_STRUCT_EMPTY(FOnConnectType);
}
