// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "OnDisconnectType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FOnDisconnectType
{
    GENERATED_BODY()

    FORCEINLINE bool operator==(const FOnDisconnectType& Other) const
    {
        return true;
    }

    FORCEINLINE bool operator!=(const FOnDisconnectType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FOnDisconnectType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param OnDisconnectType The FOnDisconnectType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FOnDisconnectType& OnDisconnectType)
{
    return 0; // Empty struct
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FOnDisconnectType);

    UE_SPACETIMEDB_STRUCT_EMPTY(FOnDisconnectType);
}
