// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "RecordUnrealRoundResultType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FRecordUnrealRoundResultType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString SessionId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Answer;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Status;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 WinnerPlayerNumber = 0;

    FORCEINLINE bool operator==(const FRecordUnrealRoundResultType& Other) const
    {
        return SessionId == Other.SessionId && Round == Other.Round && Answer == Other.Answer && Status == Other.Status && WinnerPlayerNumber == Other.WinnerPlayerNumber;
    }

    FORCEINLINE bool operator!=(const FRecordUnrealRoundResultType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FRecordUnrealRoundResultType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param RecordUnrealRoundResultType The FRecordUnrealRoundResultType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FRecordUnrealRoundResultType& RecordUnrealRoundResultType)
{
    uint32 Hash = GetTypeHash(RecordUnrealRoundResultType.SessionId);
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealRoundResultType.Round));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealRoundResultType.Answer));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealRoundResultType.Status));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealRoundResultType.WinnerPlayerNumber));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FRecordUnrealRoundResultType);

    UE_SPACETIMEDB_STRUCT(FRecordUnrealRoundResultType, SessionId, Round, Answer, Status, WinnerPlayerNumber);
}
