// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "RecordUnrealGuessType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FRecordUnrealGuessType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString SessionId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 PlayerNumber = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Guess;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Strikes = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Balls = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 AttemptNumber = 0;

    FORCEINLINE bool operator==(const FRecordUnrealGuessType& Other) const
    {
        return SessionId == Other.SessionId && Round == Other.Round && PlayerNumber == Other.PlayerNumber && Guess == Other.Guess && Strikes == Other.Strikes && Balls == Other.Balls && AttemptNumber == Other.AttemptNumber;
    }

    FORCEINLINE bool operator!=(const FRecordUnrealGuessType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FRecordUnrealGuessType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param RecordUnrealGuessType The FRecordUnrealGuessType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FRecordUnrealGuessType& RecordUnrealGuessType)
{
    uint32 Hash = GetTypeHash(RecordUnrealGuessType.SessionId);
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealGuessType.Round));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealGuessType.PlayerNumber));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealGuessType.Guess));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealGuessType.Strikes));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealGuessType.Balls));
    Hash = HashCombine(Hash, GetTypeHash(RecordUnrealGuessType.AttemptNumber));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FRecordUnrealGuessType);

    UE_SPACETIMEDB_STRUCT(FRecordUnrealGuessType, SessionId, Round, PlayerNumber, Guess, Strikes, Balls, AttemptNumber);
}
