// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "SetNameType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FSetNameType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Name;

    FORCEINLINE bool operator==(const FSetNameType& Other) const
    {
        return Name == Other.Name;
    }

    FORCEINLINE bool operator!=(const FSetNameType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FSetNameType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param SetNameType The FSetNameType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FSetNameType& SetNameType)
{
    uint32 Hash = GetTypeHash(SetNameType.Name);
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FSetNameType);

    UE_SPACETIMEDB_STRUCT(FSetNameType, Name);
}
