// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "StartNewRoundType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FStartNewRoundType
{
    GENERATED_BODY()

    FORCEINLINE bool operator==(const FStartNewRoundType& Other) const
    {
        return true;
    }

    FORCEINLINE bool operator!=(const FStartNewRoundType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FStartNewRoundType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param StartNewRoundType The FStartNewRoundType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FStartNewRoundType& StartNewRoundType)
{
    return 0; // Empty struct
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FStartNewRoundType);

    UE_SPACETIMEDB_STRUCT_EMPTY(FStartNewRoundType);
}
