// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "SubmitGuessType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FSubmitGuessType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Guess;

    FORCEINLINE bool operator==(const FSubmitGuessType& Other) const
    {
        return Guess == Other.Guess;
    }

    FORCEINLINE bool operator!=(const FSubmitGuessType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FSubmitGuessType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param SubmitGuessType The FSubmitGuessType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FSubmitGuessType& SubmitGuessType)
{
    uint32 Hash = GetTypeHash(SubmitGuessType.Guess);
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FSubmitGuessType);

    UE_SPACETIMEDB_STRUCT(FSubmitGuessType, Guess);
}
