// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Optionals/Ch4OptionalUInt32.g.h"
#include "Types/Builtins.h"
#include "UnrealRoundResultType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FUnrealRoundResultType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString SessionId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Answer;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Status;

    // NOTE: FCh4OptionalUInt32 field not exposed to Blueprint due to non-blueprintable elements
    FCh4OptionalUInt32 WinnerPlayerNumber;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp EndedAt;

    FORCEINLINE bool operator==(const FUnrealRoundResultType& Other) const
    {
        return Id == Other.Id && SessionId == Other.SessionId && Round == Other.Round && Answer == Other.Answer && Status == Other.Status && WinnerPlayerNumber == Other.WinnerPlayerNumber && EndedAt == Other.EndedAt;
    }

    FORCEINLINE bool operator!=(const FUnrealRoundResultType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUnrealRoundResultType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UnrealRoundResultType The FUnrealRoundResultType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUnrealRoundResultType& UnrealRoundResultType)
{
    uint32 Hash = GetTypeHash(UnrealRoundResultType.Id);
    Hash = HashCombine(Hash, GetTypeHash(UnrealRoundResultType.SessionId));
    Hash = HashCombine(Hash, GetTypeHash(UnrealRoundResultType.Round));
    Hash = HashCombine(Hash, GetTypeHash(UnrealRoundResultType.Answer));
    Hash = HashCombine(Hash, GetTypeHash(UnrealRoundResultType.Status));
    Hash = HashCombine(Hash, GetTypeHash(UnrealRoundResultType.WinnerPlayerNumber));
    Hash = HashCombine(Hash, GetTypeHash(UnrealRoundResultType.EndedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUnrealRoundResultType);

    UE_SPACETIMEDB_STRUCT(FUnrealRoundResultType, Id, SessionId, Round, Answer, Status, WinnerPlayerNumber, EndedAt);
}
