// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "UnrealGuessLogType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FUnrealGuessLogType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString SessionId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Round = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 PlayerNumber = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Guess;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Strikes = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Balls = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool IsOut = false;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 AttemptNumber = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp CreatedAt;

    FORCEINLINE bool operator==(const FUnrealGuessLogType& Other) const
    {
        return Id == Other.Id && SessionId == Other.SessionId && Round == Other.Round && PlayerNumber == Other.PlayerNumber && Guess == Other.Guess && Strikes == Other.Strikes && Balls == Other.Balls && IsOut == Other.IsOut && AttemptNumber == Other.AttemptNumber && CreatedAt == Other.CreatedAt;
    }

    FORCEINLINE bool operator!=(const FUnrealGuessLogType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUnrealGuessLogType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UnrealGuessLogType The FUnrealGuessLogType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUnrealGuessLogType& UnrealGuessLogType)
{
    uint32 Hash = GetTypeHash(UnrealGuessLogType.Id);
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.SessionId));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.Round));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.PlayerNumber));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.Guess));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.Strikes));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.Balls));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.IsOut));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.AttemptNumber));
    Hash = HashCombine(Hash, GetTypeHash(UnrealGuessLogType.CreatedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUnrealGuessLogType);

    UE_SPACETIMEDB_STRUCT(FUnrealGuessLogType, Id, SessionId, Round, PlayerNumber, Guess, Strikes, Balls, IsOut, AttemptNumber, CreatedAt);
}
