// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "UnrealPlayerStatsType.g.generated.h"

USTRUCT(BlueprintType)
struct CH_4_API FUnrealPlayerStatsType
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 PlayerNumber = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Wins = 0;

    FORCEINLINE bool operator==(const FUnrealPlayerStatsType& Other) const
    {
        return PlayerNumber == Other.PlayerNumber && Wins == Other.Wins;
    }

    FORCEINLINE bool operator!=(const FUnrealPlayerStatsType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUnrealPlayerStatsType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UnrealPlayerStatsType The FUnrealPlayerStatsType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUnrealPlayerStatsType& UnrealPlayerStatsType)
{
    uint32 Hash = GetTypeHash(UnrealPlayerStatsType.PlayerNumber);
    Hash = HashCombine(Hash, GetTypeHash(UnrealPlayerStatsType.Wins));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUnrealPlayerStatsType);

    UE_SPACETIMEDB_STRUCT(FUnrealPlayerStatsType, PlayerNumber, Wins);
}
