// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import SetNameReducer from "../set_name_reducer";
import StartNewRoundReducer from "../start_new_round_reducer";
import SubmitGuessReducer from "../submit_guess_reducer";

export type SetNameParams = __Infer<typeof SetNameReducer>;
export type StartNewRoundParams = __Infer<typeof StartNewRoundReducer>;
export type SubmitGuessParams = __Infer<typeof SubmitGuessReducer>;

